# Generated by Django 4.2.2 on 2023-08-02 14:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_ptr', models.OneToOneField(auto_created=True,
                                                     on_delete=django.db.models.deletion.CASCADE,
                                                     parent_link=True, primary_key=True,
                                                     serialize=False, to='ebustoolbox.station')),
            ],
            bases=('ebustoolbox.station',),
        ),

        migrations.CreateModel(
            name='MyExampleLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'My Line',
                'verbose_name_plural': 'My Lines',
            },
        ),
        migrations.CreateModel(
            name='MyExampleMultiPolygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MyExamplePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'My Point',
                'verbose_name_plural': 'My Points',
            },
        ),
    ]
    dependencies = [
        ('ebustoolbox', '0008_alter_vehicletype_v2g_curve'),
    ]

