# Generated by Django 5.0.6 on 2024-06-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ebus_map", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Station",
        ),
    ]
