# Generated by Django 5.0.4 on 2024-07-02 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ebus_map", "0002_delete_station"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyExampleLine",
        ),
        migrations.DeleteModel(
            name="MyExampleMultiPolygon",
        ),
        migrations.DeleteModel(
            name="MyExamplePoint",
        ),
    ]
