version: '3'

services:
  web:
    build: .
    command:
      - sh
      - -c
      - |
        poetry run python manage.py makemigrations
        poetry run python manage.py migrate
        poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - my-docker-postgres

  my-docker-postgres:
    image: postgis/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
      POSTGRES_USER: myprojectuser

# Note that after creating a volume, the above info cannot be changed. The volume has to be deleted, or a different volume
# name has to be used
volumes:
  postgres_data:
