site_name: WeBus
nav:
  - Home: index.md
  - Installation: install.md
  - Toolchain: toolchain.md
  - About: about.md
  - SimBA: simba.md
  - References: references.md

theme:
  name: "mkdocs"

plugins:
- search
- mkdocstrings
