[tool.poetry]
name = "django-simba"
version = "0.1.0"
description = "Django website for runnin SimBA and eFLips together"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "django_simba"}]

[tool.poetry.dependencies]
python = "^3.10"
spice_ev = " git+https://github.com/rl-institut/spice_ev@51268c639a02f2a94c418d6215376f585dd14af0"
simba = {git = "https://github.com/rl-institut/SimBA", rev = "feature/django_simba"}
Django = "^4.2.4"
django-plotly-dash = "^2.2.1"
pandas = "^2.0.3"
django-environ = ">=0.10.0, <1.0.0"
django-appconf = ">=1.0.5, <2.0.0"
djangorestframework = ">=^3.14.0, <4.0.0"
djangorestframework-mvt = ">=0.2.5, <1.0.0"
django-distill = "^3.1.3"
django-geojson = "^4.0.0"
range-key-dict = "^1.1.0"
celery = "^5.3.1"
psycopg2-binary = "^2.9.7"
matplotlib = "^3.7.2"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
flake8 = "^6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py37']
include = '^ebustoolbox/'
exclude = '''
/(
    # Exclude all directories except foo
    (?!ebustoolbox/)

    # Exclude hidden directories (starting with a dot)
    (?!\\.[^/]+/)

    # Exclude any directory starting with underscore
    (?!_[^/]+/)

    # Exclude any directory starting with double underscore
    (?!__[^/]+/)
)
'''