#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


# clear previous static files without needing a user input
poetry run python manage.py collectstatic -c --noinput
poetry run python manage.py migrate
poetry run python manage.py load_consumption
poetry run gunicorn ebusdjango.wsgi
