# Generated by Django 4.2.10 on 2024-03-06 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ebustoolbox", "0039_consumption_consumption_unique_with_scenario_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("task_id", models.UUIDField()),
                ("status", models.CharField(max_length=100)),
                ("total_work", models.IntegerField(null=True)),
                ("current_work", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=False)),
                ("running", models.BooleanField(default=True)),
                ("errors", models.JSONField(verbose_name=[])),
                (
                    "scenario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ebustoolbox.scenario",
                    ),
                ),
            ],
        ),
    ]
