# Generated by Django 4.2.10 on 2024-03-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_progress_errors_alter_progress_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progress",
            name="errors",
            field=models.JSONField(default=list, null=True, verbose_name=[]),
        ),
    ]
