# Generated by Django 4.2.10 on 2024-03-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_progress_errors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progress",
            name="total_work",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
