# Generated by Django 4.2.10 on 2024-03-21 10:08

from django.db import migrations
from django.contrib.auth.models import User
from django.conf import settings
import environ
def set_admin(apps, schema_editor):
    if User.objects.filter(is_superuser=True).exists():
        return
    env = environ.Env()
    env.read_env(str(settings.ROOT_DIR.path(".env")))
    password=env.str("DJANGO_ADMIN_PASSWORD")
    User.objects.create_superuser("admin", password=password)

def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_progress_total_work"),
    ]

    operations = [
        migrations.RunPython(set_admin, reverse),
    ]



