# Generated by Django 5.1.6 on 2025-03-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_create_super_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="progress_type",
            field=models.CharField(
                choices=[
                    ("INIT_SCHEDULE", "Init Schedule"),
                    ("RUNNING_SIMULATION", "Running Simulation"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
