# Generated by Django 5.1.6 on 2025-03-25 12:55

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_progress_progress_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now(), null=True
            ),
        ),
    ]
