# Generated by Django 5.1.6 on 2025-07-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_progress_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progress",
            name="errors",
            field=models.JSONField(default=list, null=True),
        ),
    ]
