"""Integration of eflips-impact (TCO and LCA) with the django-simba scenario graph.

The scenario the user edits in the wizard is not the scenario that is simulated::

    SOURCE_FILE -- SOURCE ---- MUTATION            (the wizard writes here)
                      |            |
                      +------------+--> SIMULATION (deepcopy(SOURCE) + mutations)

1. :func:`ensure_fleet_topology` creates the BatteryType / ChargingPointType rows that
   a TCO calculation needs and seeds every ``tco_parameters`` column from the JSON
   defaults in ``defaults/impact``. It runs on the MUTATION while the user is still in
   the wizard, so the values it writes are on screen and editable before the
   simulation starts.
2. :func:`apply_tco_mutation` carries those rows and values from the MUTATION onto the
   SIMULATION scenario during the merge, alongside the existing ``apply_*`` functions
   in :mod:`ebustoolbox.tasks`.
3. :func:`attach_charging_point_types` points Areas and Stations at the right
   ChargingPointType. This cannot happen before the simulation: Areas are generated by
   ``run_eflips`` and opportunity charging is only known from the Events that the
   simulation produces. It only sets foreign keys, never parameters.
4. :func:`calculate_tco` runs eflips-impact and returns the flat
   ``{category: EUR/revenue-km}`` dict that ``Scenario.tco_result`` and the result
   page expect.

The LCA calculation reuses all four steps: it needs the same fleet topology, the same
foreign keys, and the same annualisation. Only the parameters are its own, and they
live in a column of their own, ``lca_parameters``. :func:`ensure_lca_parameters` fills
those from ``defaults/impact/lca.json``, and :func:`calculate_lca` runs the
calculation.
"""

import json
import logging
import math
from copy import deepcopy
from functools import lru_cache
from pathlib import Path

from django.db.models import Max, Min
from django.db.transaction import atomic

from eflips.impact.lca import (
    ChargingPointTypeOverrides,
    OpenLCAData,
    VehicleTypeOverrides,
    calculate_lca as eflips_calculate_lca,
)
from eflips.impact.tco import calculate_tco as eflips_calculate_tco

from .models import (
    Area,
    BatteryType,
    ChargingPointType,
    Depot,
    EnumEnergySource,
    Event,
    Scenario,
    Station,
    Trip,
    VehicleType,
)

logger = logging.getLogger("custom")

DATA_DIR = Path(__file__).resolve().parent / "defaults" / "impact"
FLEET_DEFAULTS_PATH = DATA_DIR / "fleet.json"
TCO_DEFAULTS_PATH = DATA_DIR / "tco.json"
LCA_DEFAULTS_PATH = DATA_DIR / "lca.json"
LCA_OVERRIDES_PATH = DATA_DIR / "lca_overrides.json"

# ChargingPointType has no "type" column, so the depot/opportunity discriminator has
# to live in name_short. These are the values used in fleet.json.
DEPOT_CPT_NAME_SHORT = "DCS"
OPPORTUNITY_CPT_NAME_SHORT = "OCS"

# Key under which the depot/station site-build costs are kept inside
# Scenario.tco_parameters. See charging_infrastructure_parameters().
CHARGING_INFRASTRUCTURE_KEY = "charging_infrastructure"


# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------


@lru_cache(maxsize=None)
def load_fleet_defaults() -> dict:
    """Return the parsed contents of ``defaults/impact/fleet.json``."""
    with open(FLEET_DEFAULTS_PATH, encoding="utf-8") as f:
        return json.load(f)


@lru_cache(maxsize=None)
def load_tco_defaults() -> dict:
    """Return the parsed contents of ``defaults/impact/tco.json``."""
    with open(TCO_DEFAULTS_PATH, encoding="utf-8") as f:
        return json.load(f)


@lru_cache(maxsize=None)
def load_lca_defaults() -> OpenLCAData:
    """Return ``defaults/impact/lca.json`` as the dataclass eflips-impact builds from.

    Parsing is not a plain ``json.load``: the loader converts the electricity factors
    from per MJ to per kWh and sums the separate production and end-of-life entries,
    so the object this returns does not have the same shape as the file.
    """
    return OpenLCAData.from_json_lca(LCA_DEFAULTS_PATH)


@lru_cache(maxsize=None)
def load_lca_overrides() -> dict:
    """Return the parsed contents of ``defaults/impact/lca_overrides.json``."""
    with open(LCA_OVERRIDES_PATH, encoding="utf-8") as f:
        return json.load(f)


def _by_name_short(entries: list[dict], key: str) -> dict[str, dict]:
    """Index a list of JSON entries by one of their string fields."""
    return {entry[key]: entry for entry in entries if entry.get(key) is not None}


def _fleet_battery_defaults(name_short: str | None) -> dict:
    """Return specific_mass / chemistry for a vehicle type, falling back to the default."""
    fleet = load_fleet_defaults()
    override = _by_name_short(fleet.get("battery_types", []), "vehicle_name_short")
    entry = override.get(name_short, fleet["battery_type_default"])
    return {
        "specific_mass": float(entry["specific_mass"]),
        "chemistry": entry["chemistry"],
    }


def _tco_vehicle_type_defaults(vehicle_type: VehicleType) -> dict:
    """Return the default ``VehicleType.tco_parameters`` for a vehicle type."""
    tco = load_tco_defaults()
    override = _by_name_short(tco.get("vehicle_types", []), "name_short")
    entry = override.get(vehicle_type.name_short)
    if entry is not None:
        return {k: v for k, v in entry.items() if k != "name_short"}
    if vehicle_type.energy_source == EnumEnergySource.DIESEL:
        return deepcopy(tco["vehicle_type_default_diesel"])
    return deepcopy(tco["vehicle_type_default"])


def _tco_battery_type_defaults(name_short: str | None) -> dict:
    """Return the default ``BatteryType.tco_parameters`` for a vehicle type."""
    tco = load_tco_defaults()
    override = _by_name_short(tco.get("battery_types", []), "vehicle_name_short")
    entry = override.get(name_short)
    if entry is not None:
        return {k: v for k, v in entry.items() if k != "vehicle_name_short"}
    return deepcopy(tco["battery_type_default"])


def scenario_tco_defaults() -> dict:
    """Return the default ``Scenario.tco_parameters``."""
    return deepcopy(load_tco_defaults()["scenario"])


def _lca_vehicle_type_overrides(vehicle_type: VehicleType) -> VehicleTypeOverrides:
    """Return the per-vehicle-type LCA values that are not openLCA emission factors.

    Consumption is left at its default of zero here and written in after the
    simulation by :func:`_write_lca_consumption`.
    """
    overrides = load_lca_overrides()
    entry = _by_name_short(overrides.get("vehicle_types", []), "name_short").get(
        vehicle_type.name_short
    )
    if entry is None:
        if vehicle_type.energy_source == EnumEnergySource.DIESEL:
            entry = overrides["vehicle_type_default_diesel"]
        else:
            entry = overrides["vehicle_type_default"]

    return VehicleTypeOverrides(
        motor_rated_power_kw=float(entry["motor_rated_power_kw"]),
        vehicle_lifetime_years=float(entry["vehicle_lifetime_years"]),
        motor_power_to_weight_ratio_kw_per_kg=entry.get("motor_power_to_weight_ratio_kw_per_kg"),
        diesel_consumption_kg_per_km=entry.get("diesel_consumption_kg_per_km"),
    )


def _lca_charging_point_type_overrides(name_short: str | None) -> ChargingPointTypeOverrides:
    """Return the LCA values for one charging point type.

    Split by depot versus opportunity, which eflips-impact's own writer does not do:
    it applies the opportunity values to every charging point type in the scenario.
    The difference is the concrete foundation, which an indoor depot charger does not
    have.
    """
    entries = load_lca_overrides()["charging_point_types"]
    entry = entries["depot"] if name_short == DEPOT_CPT_NAME_SHORT else entries["opportunity"]
    return ChargingPointTypeOverrides(
        infrastructure_lifetime_years=float(entry["infrastructure_lifetime_years"]),
        foundation_volume_per_point_m3=float(entry["foundation_volume_per_point_m3"]),
    )


# ---------------------------------------------------------------------------
# Step 1: pre-simulation fleet topology
# ---------------------------------------------------------------------------


@atomic()
def ensure_fleet_topology(scenario: Scenario) -> None:
    """Create the fleet rows a TCO calculation needs, if the scenario has none.

    Idempotent and non-destructive: existing rows and non-default parameter values
    are never overwritten, so it is safe to call on every request and again from the
    toolchain. It is called from :class:`ebustoolbox.views.CostsView` so the values
    it writes are on screen and editable before the user starts the simulation.

    Creates one :class:`~ebustoolbox.models.BatteryType` per battery-electric vehicle
    type that has none, one :class:`~ebustoolbox.models.ChargingPointType` per
    charging type, and seeds the ``tco_parameters`` of the scenario, its vehicle
    types and its stations from ``defaults/impact/tco.json``.

    :param scenario: The scenario to complete. In the wizard this is the MUTATION.
    """
    _ensure_scenario_parameters(scenario)
    _ensure_battery_types(scenario)
    _ensure_charging_point_types(scenario)
    _ensure_station_parameters(scenario)


def _seed_from_json(current: dict | None, json_defaults: dict, model_default: dict | None) -> dict:
    """Merge JSON defaults into a stored ``tco_parameters`` value, key by key.

    Postgres fills these columns from the model's ``db_default`` at INSERT, so a row
    is never empty by the time this runs; a plain "keep whatever is stored" merge
    would make ``defaults/impact/tco.json`` inert and leave two competing sources of
    truth for the same numbers. A key that is missing, or still holds the model
    default, therefore counts as unset and takes the JSON value. Any other value is
    the user's and is kept.

    The comparison is per key rather than on the whole dict, so a row written before a
    key was added to the model default is not mistaken for a user edit. Keys present
    only in the stored value (such as the ``procurement_cost_diesel`` left over from
    eflips-tco) are carried through untouched.

    A user who types a value identical to the model default loses that edit on the
    next call. Distinguishing the two would need the edits tracked separately, which
    is not worth a column here.

    :param current: The stored value, possibly ``None``.
    :param json_defaults: The corresponding block of ``defaults/impact/tco.json``.
    :param model_default: The field's ``db_default``.
    :returns: The value to store.
    """
    current = current or {}
    model_default = model_default or {}

    result = dict(current)
    for key, json_value in json_defaults.items():
        if isinstance(json_value, dict):
            # fuel_cost, cost_escalation_rate, ... follow the same rule one level down.
            result[key] = _seed_from_json(current.get(key), json_value, model_default.get(key))
        elif key not in current or current[key] == model_default.get(key):
            result[key] = json_value
    return result


def _ensure_scenario_parameters(scenario: Scenario) -> None:
    """Seed ``Scenario.tco_parameters`` from ``defaults/impact/tco.json``.

    Also backfills ``eta_avail`` for scenarios stored before it was added, which
    ``TCOCalculator`` reads unconditionally and would otherwise fail on.
    """
    merged = _seed_from_json(
        scenario.tco_parameters,
        scenario_tco_defaults(),
        Scenario._meta.get_field("tco_parameters").db_default,
    )
    if merged != scenario.tco_parameters:
        scenario.tco_parameters = merged
        scenario.save(update_fields=["tco_parameters"])


def _ensure_battery_types(scenario: Scenario) -> None:
    """Create and assign a BatteryType for every BEB vehicle type that lacks one.

    One row per vehicle type rather than one shared row: eflips-impact prices a
    battery as ``procurement_cost * VehicleType.battery_capacity``, so the parameters
    are only meaningful per vehicle type.
    """
    for vehicle_type in VehicleType.objects.filter(scenario=scenario):
        update_fields = []

        merged = _seed_from_json(
            vehicle_type.tco_parameters,
            _tco_vehicle_type_defaults(vehicle_type),
            VehicleType._meta.get_field("tco_parameters").db_default,
        )
        if merged != vehicle_type.tco_parameters:
            vehicle_type.tco_parameters = merged
            update_fields.append("tco_parameters")

        is_beb = vehicle_type.energy_source == EnumEnergySource.BATTERY_ELECTRIC
        if is_beb and vehicle_type.battery_type_id is None:
            fleet_defaults = _fleet_battery_defaults(vehicle_type.name_short)
            battery_type = BatteryType.objects.create(
                scenario=scenario,
                specific_mass=fleet_defaults["specific_mass"],
                chemistry=fleet_defaults["chemistry"],
                tco_parameters=_tco_battery_type_defaults(vehicle_type.name_short),
            )
            vehicle_type.battery_type = battery_type
            update_fields.append("battery_type")
            logger.info(
                f"S.ID:{scenario.id}:Created BatteryType {battery_type.id} "
                f"for VehicleType {vehicle_type.id} ({vehicle_type.name_short})"
            )

        if update_fields:
            vehicle_type.save(update_fields=update_fields)


def _ensure_charging_point_types(scenario: Scenario) -> None:
    """Create the depot and opportunity ChargingPointType rows if they are missing.

    Both are created unconditionally. Which one is actually used is only decided
    after the simulation, in :func:`attach_charging_point_types`; an unused
    ChargingPointType contributes nothing to the TCO because eflips-impact prices it
    from the Areas and Stations pointing at it.
    """
    tco_defaults = load_tco_defaults()["charging_point_types"]
    for entry in load_fleet_defaults()["charging_point_types"]:
        # name_short carries the type, so it is the lookup key rather than a default.
        _, created = ChargingPointType.objects.get_or_create(
            scenario=scenario,
            name_short=entry["name_short"],
            defaults={
                "name": entry["name"],
                "tco_parameters": deepcopy(tco_defaults[entry["type"]]),
            },
        )
        if created:
            logger.info(f"S.ID:{scenario.id}:Created ChargingPointType '{entry['name_short']}'")


def charging_infrastructure_parameters(scenario: Scenario) -> dict:
    """Return the site-build costs for this scenario, keyed ``depot`` / ``station``.

    Stored on the scenario rather than per station because the wizard has to collect
    them before it is known which station becomes a depot — the costs page runs before
    the depot page, and the :class:`~ebustoolbox.models.Depot` rows themselves are only
    created during the simulation. :func:`_ensure_station_parameters` distributes them
    onto the stations once that is settled.

    eflips-impact reads named keys out of ``Scenario.tco_parameters`` and ignores the
    rest, so keeping them there costs nothing and means they ride along with the
    existing mutation carry-over instead of needing one of their own.
    """
    defaults = load_tco_defaults()["charging_infrastructure"]
    stored = (scenario.tco_parameters or {}).get(CHARGING_INFRASTRUCTURE_KEY) or {}
    return {key: {**value, **(stored.get(key) or {})} for key, value in defaults.items()}


def _ensure_station_parameters(scenario: Scenario) -> None:
    """Distribute the site-build costs onto the scenario's stations.

    These are the costs of building the charging site itself, which eflips-impact
    prices per station and groups by the value of this column. The model's
    ``db_default`` has ``procurement_cost: 0``, so without this every station would be
    free.

    Which stations are depots is only known once a :class:`~ebustoolbox.models.Depot`
    exists, and that happens during the simulation — after this has already run once on
    the MUTATION, where every station necessarily looks like an ordinary charging
    station. Since both parameter sets live on the scenario, the toolchain's second
    call simply re-runs the split and the depot stations pick up the depot values then.
    """
    parameters = charging_infrastructure_parameters(scenario)
    depot_station_ids = set(
        Depot.objects.filter(scenario=scenario).values_list("station_id", flat=True)
    )

    for station in Station.objects.filter(scenario=scenario):
        wanted = deepcopy(parameters["depot" if station.id in depot_station_ids else "station"])
        if station.tco_parameters == wanted:
            continue
        station.tco_parameters = wanted
        station.save(update_fields=["tco_parameters"])


# ---------------------------------------------------------------------------
# Step 2: carry the user's values onto the simulated scenario
# ---------------------------------------------------------------------------


def apply_tco_mutation(mutation: Scenario, child: Scenario, stack: dict) -> None:
    """Apply the mutation's TCO data to the simulated scenario.

    Counterpart of ``apply_vehicle_mutation`` / ``apply_station_mutation``, called
    from ``create_child_from_mutation``. The child is a deepcopy of the SOURCE
    scenario, which owns none of these rows, so without this the user's cost inputs
    never reach the simulation.

    ``VehicleType.tco_parameters`` and ``Station.tco_parameters`` are already carried
    by the two functions above, which copy whole rows. That is also why the
    ``battery_type_id`` / ``charging_point_type_id`` of the child point at the
    *mutation's* rows at this point — a cross-scenario reference that would cascade
    into the simulated scenario when the mutation is deleted. Repairing those is the
    second half of this function, so it has to run after ``apply_vehicle_mutation``.

    :param mutation: The MUTATION scenario the wizard wrote to.
    :param child: The SIMULATION scenario, a deepcopy of the SOURCE.
    :param stack: Deepcopy bookkeeping, unused here but kept for signature symmetry
        with the other ``apply_*`` functions.
    """
    child.tco_parameters = deepcopy(mutation.tco_parameters)

    battery_type_map = {}
    for battery_type in BatteryType.objects.filter(scenario=mutation):
        old_id = battery_type.id
        battery_type.id = None
        battery_type.scenario = child
        battery_type.save()
        battery_type_map[old_id] = battery_type.id

    charging_point_type_map = {}
    for charging_point_type in ChargingPointType.objects.filter(scenario=mutation):
        old_id = charging_point_type.id
        charging_point_type.id = None
        charging_point_type.scenario = child
        charging_point_type.save()
        charging_point_type_map[old_id] = charging_point_type.id

    for vehicle_type in VehicleType.objects.filter(scenario=child, battery_type__isnull=False):
        vehicle_type.battery_type_id = battery_type_map.get(vehicle_type.battery_type_id)
        vehicle_type.save(update_fields=["battery_type"])

    for station in Station.objects.filter(scenario=child, charging_point_type__isnull=False):
        station.charging_point_type_id = charging_point_type_map.get(station.charging_point_type_id)
        station.save(update_fields=["charging_point_type"])

    logger.info(
        f"S.ID:{child.id}:Applied TCO mutation from S.ID:{mutation.id} "
        f"({len(battery_type_map)} battery types, "
        f"{len(charging_point_type_map)} charging point types)"
    )


# ---------------------------------------------------------------------------
# Step 3: attach charging point types to the simulated topology
# ---------------------------------------------------------------------------


@atomic()
def attach_charging_point_types(scenario: Scenario) -> None:
    """Point the simulated Areas and Stations at their ChargingPointType.

    Runs after the simulation and before the TCO calculation, because neither target
    exists earlier: Areas are generated by ``run_eflips`` and opportunity charging is
    only visible in the Events the simulation produces.

    Mirrors the assignment rules of ``eflips.impact.utils.complete_fleet`` — depot
    charging points go to every Area with an electric charging Process, opportunity
    charging points to every Station with a ``CHARGING_OPPORTUNITY`` event — but only
    assigns foreign keys. The parameters on the rows themselves were set before the
    simulation and carried over by :func:`apply_tco_mutation`.

    :param scenario: The SIMULATION scenario, after ``apply_depot_strategy``.
    """
    charging_point_types = {
        cpt.name_short: cpt for cpt in ChargingPointType.objects.filter(scenario=scenario)
    }

    depot_cpt = charging_point_types.get(DEPOT_CPT_NAME_SHORT)
    if depot_cpt is not None:
        depot_areas = Area.objects.filter(
            scenario=scenario, processes__electric_power__isnull=False
        ).distinct()
        updated = depot_areas.update(charging_point_type=depot_cpt)
        logger.info(f"S.ID:{scenario.id}:Attached depot charging point to {updated} areas")
    else:
        logger.warning(f"S.ID:{scenario.id}:No depot ChargingPointType to attach")

    opportunity_cpt = charging_point_types.get(OPPORTUNITY_CPT_NAME_SHORT)
    if opportunity_cpt is not None:
        opportunity_station_ids = (
            Event.objects.filter(scenario=scenario, event_type="CHARGING_OPPORTUNITY")
            .exclude(station__isnull=True)
            .values_list("station_id", flat=True)
            .distinct()
        )
        updated = Station.objects.filter(
            scenario=scenario, id__in=list(opportunity_station_ids)
        ).update(charging_point_type=opportunity_cpt)
        logger.info(f"S.ID:{scenario.id}:Attached opportunity charging point to {updated} stations")
    else:
        logger.warning(f"S.ID:{scenario.id}:No opportunity ChargingPointType to attach")


# ---------------------------------------------------------------------------
# Step 4: the calculation
# ---------------------------------------------------------------------------


def get_scaling_factor(scenario: Scenario) -> float:
    """Return the annualisation factor ``365 / simulated_days`` for a scenario.

    eflips-impact derives this from the span between the first and last trip
    *departure*, which understates a single service day: a day whose first bus leaves
    at 20:25 and whose last leaves at 06:26 spans 0.42 days, giving a factor of ~875
    instead of 365. Capital cost per revenue-km scales with the reciprocal of this
    number, so the capex/opex split of the result would be set by that artifact.
    Rounding the span up to whole days keeps a one-day schedule at 365.

    :param scenario: The scenario being calculated.
    :returns: ``365.0 / simulated_days``, with a floor of one day.
    """
    span = Trip.objects.filter(scenario=scenario).aggregate(
        first=Min("departure_time"), last=Max("departure_time")
    )
    if span["first"] is None or span["last"] is None:
        logger.warning(f"S.ID:{scenario.id}:No trips found, assuming a one-day simulation for TCO")
        return 365.0
    days = (span["last"] - span["first"]).total_seconds() / 86_400.0
    return 365.0 / max(1.0, math.ceil(days))


def _electricity_consumption(vehicle_type: VehicleType) -> float | None:
    """Return a battery-electric vehicle type's consumption in kWh/km.

    Taken from the vehicle type if it carries a constant, and otherwise measured off
    the simulated driving events. Shared by the TCO and LCA writers so that the two
    calculations cannot end up describing the same fleet with different energy use.

    :returns: kWh/km, or ``None`` if the scenario has not been simulated far enough to
        measure one and the vehicle type has no constant either.
    """
    if vehicle_type.consumption is not None:
        return vehicle_type.consumption

    energy_kwh = sum(
        event.get_energy_delta()
        for event in Event.objects.filter(vehicle_type=vehicle_type, event_type="DRIVING")
    )
    distance = vehicle_type.get_total_distance_km
    if not distance:
        return None
    # Driving events lose energy, so the delta is negative.
    return -energy_kwh / distance


def _write_energy_consumption(scenario: Scenario) -> None:
    """Write the per-vehicle-type average consumption eflips-impact reads.

    ``TCOCalculator`` runs in ``"constant"`` mode and looks for
    ``average_electricity_consumption`` (or ``average_diesel_consumption`` for diesel
    vehicle types) in ``VehicleType.tco_parameters``; a missing value is logged and
    treated as zero, which silently zeroes the energy cost.
    """
    for vehicle_type in VehicleType.objects.filter(scenario=scenario):
        parameters = vehicle_type.tco_parameters or {}

        if vehicle_type.energy_source == EnumEnergySource.DIESEL:
            # No simulated diesel consumption exists; keep whatever was configured.
            if parameters.get("average_diesel_consumption") is None:
                parameters["average_diesel_consumption"] = _tco_vehicle_type_defaults(vehicle_type)[
                    "average_diesel_consumption"
                ]
        else:
            consumption = _electricity_consumption(vehicle_type)
            if consumption is not None:
                parameters["average_electricity_consumption"] = consumption
            else:
                logger.warning(
                    f"S.ID:{scenario.id}:VehicleType {vehicle_type.id} has no distance; "
                    "falling back to the configured consumption for TCO"
                )
                parameters.setdefault(
                    "average_electricity_consumption",
                    _tco_vehicle_type_defaults(vehicle_type)["average_electricity_consumption"],
                )

        vehicle_type.tco_parameters = parameters
        vehicle_type.save(update_fields=["tco_parameters"])


def calculate_tco(scenario: Scenario) -> dict:
    """Run the eflips-impact TCO calculation for a simulated scenario.

    :param scenario: A simulated scenario, after :func:`attach_charging_point_types`.
    :returns: ``{cost_category: EUR per revenue-km}``, the flat shape stored in
        ``Scenario.tco_result`` and read by the result page.
    """
    from ebustoolbox.tasks import create_db_url  # avoids a circular import

    _ensure_scenario_parameters(scenario)
    _write_energy_consumption(scenario)

    result = eflips_calculate_tco(
        scenario.id,
        database_url=create_db_url(),
        scaling_factor=get_scaling_factor(scenario),
    )
    return tco_result_to_dict(result)


def tco_result_to_dict(result) -> dict:
    """Flatten a :class:`eflips.impact.tco.TCOResult` for storage and the frontend.

    The result page iterates ``Object.keys(tco_result)`` and treats every value as a
    bar segment, so the stored dict has to stay a flat category-to-number mapping.

    :param result: The ``TCOResult`` returned by eflips-impact.
    :returns: ``{category name: EUR per revenue-km}``.
    """
    return {category.name: value for category, value in result.tco_by_type_per_revenue_km.items()}


# ---------------------------------------------------------------------------
# LCA
# ---------------------------------------------------------------------------


@atomic()
def ensure_lca_parameters(scenario: Scenario) -> None:
    """Fill ``lca_parameters`` on every row of a scenario that needs one.

    The rows themselves are not created here: :func:`ensure_fleet_topology` owns that,
    and this has to run after it. ``calculate_lca`` raises rather than falling back
    when a vehicle type, battery type or charging point type it reaches has no
    parameters, so a scenario is either completely parameterised or not calculable.

    Deliberately not built on eflips-impact's own ``init_lca_params``. That one keys
    its per-vehicle-type values by ``name_short`` and writes *nothing at all* -- for
    any entity in the scenario -- if one battery-electric vehicle type is missing from
    the file. Fleets here are user uploads with arbitrary names, so that would be the
    normal case rather than the exception. Working from the same file through the
    lower-level constructors keeps the name lookup optional, and lets depot and
    opportunity charging points be told apart, which ``init_lca_params`` does not do.

    Values are replaced rather than merged: the JSON file is meant to be the only
    source of them. Nothing here preserves a stored value, because nothing can edit
    these -- unlike the TCO parameters, they have no form behind them.

    :param scenario: The scenario to parameterise, after ``ensure_fleet_topology``.
    """
    data = load_lca_defaults()
    year = int(load_lca_overrides()["year"])

    for vehicle_type in VehicleType.objects.filter(scenario=scenario):
        overrides = _lca_vehicle_type_overrides(vehicle_type)
        if vehicle_type.energy_source == EnumEnergySource.DIESEL:
            parameters = data.make_vehicle_type_lca_parameters_diesel(overrides)
        else:
            parameters = data.make_vehicle_type_lca_parameters_beb(year, overrides)
        vehicle_type.lca_parameters = parameters.to_dict()
        vehicle_type.save(update_fields=["lca_parameters"])

    for battery_type in BatteryType.objects.filter(scenario=scenario):
        # chemistry picks the emission factors: anything starting with "NMC" is NMC,
        # everything else is treated as LFP.
        battery_type.lca_parameters = data.make_battery_type_lca_parameters(
            battery_type.chemistry
        ).to_dict()
        battery_type.save(update_fields=["lca_parameters"])

    for charging_point_type in ChargingPointType.objects.filter(scenario=scenario):
        charging_point_type.lca_parameters = data.make_charging_point_type_lca_parameters(
            _lca_charging_point_type_overrides(charging_point_type.name_short)
        ).to_dict()
        charging_point_type.save(update_fields=["lca_parameters"])

    logger.info(f"S.ID:{scenario.id}:Seeded LCA parameters from {LCA_DEFAULTS_PATH.name}")


def _write_lca_consumption(scenario: Scenario) -> None:
    """Write the measured consumption into ``VehicleType.lca_parameters``.

    The counterpart of :func:`_write_energy_consumption`, using the same value from
    :func:`_electricity_consumption`. It is seeded as zero by
    :func:`ensure_lca_parameters` because it is a result of the simulation rather than
    a configured default, and zero here would silently remove the entire use phase of
    a battery-electric fleet from the result.

    Diesel consumption is not touched: nothing simulates it, so it keeps the value
    from ``lca_overrides.json``. Note the unit differs from the TCO parameter of the
    same name -- kg/km here, litres/km there.
    """
    for vehicle_type in VehicleType.objects.filter(scenario=scenario):
        if vehicle_type.energy_source == EnumEnergySource.DIESEL:
            continue

        parameters = vehicle_type.lca_parameters or {}
        consumption = _electricity_consumption(vehicle_type)
        if consumption is None:
            logger.warning(
                f"S.ID:{scenario.id}:VehicleType {vehicle_type.id} has no distance; "
                "its use-phase emissions will be zero"
            )
            continue

        parameters["average_consumption_kwh_per_km"] = consumption
        vehicle_type.lca_parameters = parameters
        vehicle_type.save(update_fields=["lca_parameters"])


def _write_charging_places(scenario: Scenario) -> None:
    """Fill in the plug count of opportunity stations that have none.

    ``amount_charging_places`` is optional on the stations page, and most scenarios
    reach the calculation with it unset. eflips-impact reads it as the number of plugs
    to build -- one user unit and one concrete foundation each -- and, while it checks
    for ``None`` before warning about an oversized station, it then multiplies with it
    unguarded, so an unset value is a ``TypeError`` rather than a missing figure.

    The value written is the peak number of buses charging at the station at once,
    which is the smallest plug count that could have served the simulated schedule.
    A count the user did enter is left alone; this only runs on the simulated
    scenario, never on the one the wizard edits.
    """
    depot_station_ids = set(
        Depot.objects.filter(scenario=scenario).values_list("station_id", flat=True)
    )
    stations = (
        Station.objects.filter(scenario=scenario, is_electrified=True)
        .exclude(id__in=depot_station_ids)
        .exclude(charging_point_type__isnull=True)
    )

    for station in stations:
        if station.amount_charging_places:
            continue

        # A charge ending exactly as another begins reuses the plug, so an end is
        # sorted before a start at the same instant.
        deltas = []
        for time_start, time_end in Event.objects.filter(
            scenario=scenario, station=station, event_type="CHARGING_OPPORTUNITY"
        ).values_list("time_start", "time_end"):
            deltas.append((time_start, 1))
            deltas.append((time_end, -1))
        deltas.sort(key=lambda point: (point[0], point[1]))

        peak = simultaneous = 0
        for _, delta in deltas:
            simultaneous += delta
            peak = max(peak, simultaneous)

        if peak == 0:
            continue

        station.amount_charging_places = peak
        station.save(update_fields=["amount_charging_places"])
        logger.info(
            f"S.ID:{scenario.id}:Station {station.id} had no charging places; "
            f"using the simulated peak of {peak}"
        )


def _eta_avail(scenario: Scenario) -> float:
    """Return the technical availability factor to size the fleet with.

    Read from ``Scenario.tco_parameters`` so that both calculations scale the
    simulated vehicle count the same way -- LCA takes
    ``ceil(n_ready / eta_avail)`` vehicles as built, and a value differing from the
    TCO one would have the two costing different fleets. ``lca.json`` carries its own
    figure, used only when the scenario has none.
    """
    stored = (scenario.tco_parameters or {}).get("eta_avail")
    if stored:
        return float(stored)
    return float(load_lca_defaults().eta_avail)


def calculate_lca(scenario: Scenario) -> dict:
    """Run the eflips-impact LCA calculation for a simulated scenario.

    Shares the annualisation with :func:`calculate_tco` -- same scaling factor, same
    availability factor -- so that the two describe one fleet over one year.

    :param scenario: A simulated scenario, after :func:`attach_charging_point_types`.
    :returns: The nested dict described in :func:`lca_result_to_dict`.
    """
    from ebustoolbox.tasks import create_db_url  # avoids a circular import

    ensure_lca_parameters(scenario)
    _write_lca_consumption(scenario)
    _write_charging_places(scenario)

    result = eflips_calculate_lca(
        scenario.id,
        database_url=create_db_url(),
        scaling_factor=get_scaling_factor(scenario),
        eta_avail=_eta_avail(scenario),
    )
    return lca_result_to_dict(result)


def lca_result_to_dict(result) -> dict:
    """Flatten an ``LCAResult`` for storage and the frontend.

    ``LCAResult.items`` are annual fleet totals rather than per-revenue-km figures;
    the three groupings below are the normalised ones. Each maps a group name to the
    eight impact categories (``gwp``, ``pm``, ``pocp``, ``ap``, ``ep_freshwater``,
    ``ep_marine``, ``fuel``, ``water``), all per revenue-km.

    :param result: The ``LCAResult`` returned by eflips-impact.
    :returns: ``{"total": {...}, "by_scope": {...}, "by_type": {...},
        "revenue_km": {...}}``.
    """
    return {
        "total": result.total_per_revenue_km.to_dict(),
        "by_scope": {
            scope.name: vector.to_dict() for scope, vector in result.emissions_by_scope.items()
        },
        "by_type": {
            item.name: vector.to_dict() for item, vector in result.emissions_by_type.items()
        },
        "revenue_km": dict(result.revenue_km),
    }
