"""Integration of eflips-impact (TCO) with the django-simba scenario graph.

The scenario the user edits in the wizard is not the scenario that is simulated::

    SOURCE_FILE -- SOURCE ---- MUTATION            (the wizard writes here)
                      |            |
                      +------------+--> SIMULATION (deepcopy(SOURCE) + mutations)

1. :func:`ensure_fleet_topology` creates the BatteryType / ChargingPointType rows that
   a TCO calculation needs and seeds every ``tco_parameters`` column from the JSON
   defaults in ``defaults/impact``. It runs on the MUTATION while the user is still in
   the wizard, so the values it writes are on screen and editable before the
   simulation starts.
2. :func:`apply_tco_mutation` carries those rows and values from the MUTATION onto the
   SIMULATION scenario during the merge, alongside the existing ``apply_*`` functions
   in :mod:`ebustoolbox.tasks`.
3. :func:`attach_charging_point_types` points Areas and Stations at the right
   ChargingPointType. This cannot happen before the simulation: Areas are generated by
   ``run_eflips`` and opportunity charging is only known from the Events that the
   simulation produces. It only sets foreign keys, never parameters.
4. :func:`calculate_tco` runs eflips-impact and returns the flat
   ``{category: EUR/revenue-km}`` dict that ``Scenario.tco_result`` and the result
   page expect.
"""

import json
import logging
import math
from copy import deepcopy
from functools import lru_cache
from pathlib import Path

from django.db.models import Max, Min
from django.db.transaction import atomic

from eflips.impact.tco import calculate_tco as eflips_calculate_tco

from .models import (
    Area,
    BatteryType,
    ChargingPointType,
    Depot,
    EnumEnergySource,
    Event,
    Scenario,
    Station,
    Trip,
    VehicleType,
)

logger = logging.getLogger("custom")

DATA_DIR = Path(__file__).resolve().parent / "defaults" / "impact"
FLEET_DEFAULTS_PATH = DATA_DIR / "fleet.json"
TCO_DEFAULTS_PATH = DATA_DIR / "tco.json"

# ChargingPointType has no "type" column, so the depot/opportunity discriminator has
# to live in name_short. These are the values used in fleet.json.
DEPOT_CPT_NAME_SHORT = "DCS"
OPPORTUNITY_CPT_NAME_SHORT = "OCS"

# Key under which the depot/station site-build costs are kept inside
# Scenario.tco_parameters. See charging_infrastructure_parameters().
CHARGING_INFRASTRUCTURE_KEY = "charging_infrastructure"


# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------


@lru_cache(maxsize=None)
def load_fleet_defaults() -> dict:
    """Return the parsed contents of ``defaults/impact/fleet.json``."""
    with open(FLEET_DEFAULTS_PATH, encoding="utf-8") as f:
        return json.load(f)


@lru_cache(maxsize=None)
def load_tco_defaults() -> dict:
    """Return the parsed contents of ``defaults/impact/tco.json``."""
    with open(TCO_DEFAULTS_PATH, encoding="utf-8") as f:
        return json.load(f)


def _by_name_short(entries: list[dict], key: str) -> dict[str, dict]:
    """Index a list of JSON entries by one of their string fields."""
    return {entry[key]: entry for entry in entries if entry.get(key) is not None}


def _fleet_battery_defaults(name_short: str | None) -> dict:
    """Return specific_mass / chemistry for a vehicle type, falling back to the default."""
    fleet = load_fleet_defaults()
    override = _by_name_short(fleet.get("battery_types", []), "vehicle_name_short")
    entry = override.get(name_short, fleet["battery_type_default"])
    return {
        "specific_mass": float(entry["specific_mass"]),
        "chemistry": entry["chemistry"],
    }


def _tco_vehicle_type_defaults(vehicle_type: VehicleType) -> dict:
    """Return the default ``VehicleType.tco_parameters`` for a vehicle type."""
    tco = load_tco_defaults()
    override = _by_name_short(tco.get("vehicle_types", []), "name_short")
    entry = override.get(vehicle_type.name_short)
    if entry is not None:
        return {k: v for k, v in entry.items() if k != "name_short"}
    if vehicle_type.energy_source == EnumEnergySource.DIESEL:
        return deepcopy(tco["vehicle_type_default_diesel"])
    return deepcopy(tco["vehicle_type_default"])


def _tco_battery_type_defaults(name_short: str | None) -> dict:
    """Return the default ``BatteryType.tco_parameters`` for a vehicle type."""
    tco = load_tco_defaults()
    override = _by_name_short(tco.get("battery_types", []), "vehicle_name_short")
    entry = override.get(name_short)
    if entry is not None:
        return {k: v for k, v in entry.items() if k != "vehicle_name_short"}
    return deepcopy(tco["battery_type_default"])


def scenario_tco_defaults() -> dict:
    """Return the default ``Scenario.tco_parameters``."""
    return deepcopy(load_tco_defaults()["scenario"])


# ---------------------------------------------------------------------------
# Step 1: pre-simulation fleet topology
# ---------------------------------------------------------------------------


@atomic()
def ensure_fleet_topology(scenario: Scenario) -> None:
    """Create the fleet rows a TCO calculation needs, if the scenario has none.

    Idempotent and non-destructive: existing rows and non-default parameter values
    are never overwritten, so it is safe to call on every request and again from the
    toolchain. It is called from :class:`ebustoolbox.views.CostsView` so the values
    it writes are on screen and editable before the user starts the simulation.

    Creates one :class:`~ebustoolbox.models.BatteryType` per battery-electric vehicle
    type that has none, one :class:`~ebustoolbox.models.ChargingPointType` per
    charging type, and seeds the ``tco_parameters`` of the scenario, its vehicle
    types and its stations from ``defaults/impact/tco.json``.

    :param scenario: The scenario to complete. In the wizard this is the MUTATION.
    """
    _ensure_scenario_parameters(scenario)
    _ensure_battery_types(scenario)
    _ensure_charging_point_types(scenario)
    _ensure_station_parameters(scenario)


def _seed_from_json(current: dict | None, json_defaults: dict, model_default: dict | None) -> dict:
    """Merge JSON defaults into a stored ``tco_parameters`` value, key by key.

    Postgres fills these columns from the model's ``db_default`` at INSERT, so a row
    is never empty by the time this runs; a plain "keep whatever is stored" merge
    would make ``defaults/impact/tco.json`` inert and leave two competing sources of
    truth for the same numbers. A key that is missing, or still holds the model
    default, therefore counts as unset and takes the JSON value. Any other value is
    the user's and is kept.

    The comparison is per key rather than on the whole dict, so a row written before a
    key was added to the model default is not mistaken for a user edit. Keys present
    only in the stored value (such as the ``procurement_cost_diesel`` left over from
    eflips-tco) are carried through untouched.

    A user who types a value identical to the model default loses that edit on the
    next call. Distinguishing the two would need the edits tracked separately, which
    is not worth a column here.

    :param current: The stored value, possibly ``None``.
    :param json_defaults: The corresponding block of ``defaults/impact/tco.json``.
    :param model_default: The field's ``db_default``.
    :returns: The value to store.
    """
    current = current or {}
    model_default = model_default or {}

    result = dict(current)
    for key, json_value in json_defaults.items():
        if isinstance(json_value, dict):
            # fuel_cost, cost_escalation_rate, ... follow the same rule one level down.
            result[key] = _seed_from_json(current.get(key), json_value, model_default.get(key))
        elif key not in current or current[key] == model_default.get(key):
            result[key] = json_value
    return result


def _ensure_scenario_parameters(scenario: Scenario) -> None:
    """Seed ``Scenario.tco_parameters`` from ``defaults/impact/tco.json``.

    Also backfills ``eta_avail`` for scenarios stored before it was added, which
    ``TCOCalculator`` reads unconditionally and would otherwise fail on.
    """
    merged = _seed_from_json(
        scenario.tco_parameters,
        scenario_tco_defaults(),
        Scenario._meta.get_field("tco_parameters").db_default,
    )
    if merged != scenario.tco_parameters:
        scenario.tco_parameters = merged
        scenario.save(update_fields=["tco_parameters"])


def _ensure_battery_types(scenario: Scenario) -> None:
    """Create and assign a BatteryType for every BEB vehicle type that lacks one.

    One row per vehicle type rather than one shared row: eflips-impact prices a
    battery as ``procurement_cost * VehicleType.battery_capacity``, so the parameters
    are only meaningful per vehicle type.
    """
    for vehicle_type in VehicleType.objects.filter(scenario=scenario):
        update_fields = []

        merged = _seed_from_json(
            vehicle_type.tco_parameters,
            _tco_vehicle_type_defaults(vehicle_type),
            VehicleType._meta.get_field("tco_parameters").db_default,
        )
        if merged != vehicle_type.tco_parameters:
            vehicle_type.tco_parameters = merged
            update_fields.append("tco_parameters")

        is_beb = vehicle_type.energy_source == EnumEnergySource.BATTERY_ELECTRIC
        if is_beb and vehicle_type.battery_type_id is None:
            fleet_defaults = _fleet_battery_defaults(vehicle_type.name_short)
            battery_type = BatteryType.objects.create(
                scenario=scenario,
                specific_mass=fleet_defaults["specific_mass"],
                chemistry=fleet_defaults["chemistry"],
                tco_parameters=_tco_battery_type_defaults(vehicle_type.name_short),
            )
            vehicle_type.battery_type = battery_type
            update_fields.append("battery_type")
            logger.info(
                f"S.ID:{scenario.id}:Created BatteryType {battery_type.id} "
                f"for VehicleType {vehicle_type.id} ({vehicle_type.name_short})"
            )

        if update_fields:
            vehicle_type.save(update_fields=update_fields)


def _ensure_charging_point_types(scenario: Scenario) -> None:
    """Create the depot and opportunity ChargingPointType rows if they are missing.

    Both are created unconditionally. Which one is actually used is only decided
    after the simulation, in :func:`attach_charging_point_types`; an unused
    ChargingPointType contributes nothing to the TCO because eflips-impact prices it
    from the Areas and Stations pointing at it.
    """
    tco_defaults = load_tco_defaults()["charging_point_types"]
    for entry in load_fleet_defaults()["charging_point_types"]:
        # name_short carries the type, so it is the lookup key rather than a default.
        _, created = ChargingPointType.objects.get_or_create(
            scenario=scenario,
            name_short=entry["name_short"],
            defaults={
                "name": entry["name"],
                "tco_parameters": deepcopy(tco_defaults[entry["type"]]),
            },
        )
        if created:
            logger.info(f"S.ID:{scenario.id}:Created ChargingPointType '{entry['name_short']}'")


def charging_infrastructure_parameters(scenario: Scenario) -> dict:
    """Return the site-build costs for this scenario, keyed ``depot`` / ``station``.

    Stored on the scenario rather than per station because the wizard has to collect
    them before it is known which station becomes a depot — the costs page runs before
    the depot page, and the :class:`~ebustoolbox.models.Depot` rows themselves are only
    created during the simulation. :func:`_ensure_station_parameters` distributes them
    onto the stations once that is settled.

    eflips-impact reads named keys out of ``Scenario.tco_parameters`` and ignores the
    rest, so keeping them there costs nothing and means they ride along with the
    existing mutation carry-over instead of needing one of their own.
    """
    defaults = load_tco_defaults()["charging_infrastructure"]
    stored = (scenario.tco_parameters or {}).get(CHARGING_INFRASTRUCTURE_KEY) or {}
    return {key: {**value, **(stored.get(key) or {})} for key, value in defaults.items()}


def _ensure_station_parameters(scenario: Scenario) -> None:
    """Distribute the site-build costs onto the scenario's stations.

    These are the costs of building the charging site itself, which eflips-impact
    prices per station and groups by the value of this column. The model's
    ``db_default`` has ``procurement_cost: 0``, so without this every station would be
    free.

    Which stations are depots is only known once a :class:`~ebustoolbox.models.Depot`
    exists, and that happens during the simulation — after this has already run once on
    the MUTATION, where every station necessarily looks like an ordinary charging
    station. Since both parameter sets live on the scenario, the toolchain's second
    call simply re-runs the split and the depot stations pick up the depot values then.
    """
    parameters = charging_infrastructure_parameters(scenario)
    depot_station_ids = set(
        Depot.objects.filter(scenario=scenario).values_list("station_id", flat=True)
    )

    for station in Station.objects.filter(scenario=scenario):
        wanted = deepcopy(parameters["depot" if station.id in depot_station_ids else "station"])
        if station.tco_parameters == wanted:
            continue
        station.tco_parameters = wanted
        station.save(update_fields=["tco_parameters"])


# ---------------------------------------------------------------------------
# Step 2: carry the user's values onto the simulated scenario
# ---------------------------------------------------------------------------


def apply_tco_mutation(mutation: Scenario, child: Scenario, stack: dict) -> None:
    """Apply the mutation's TCO data to the simulated scenario.

    Counterpart of ``apply_vehicle_mutation`` / ``apply_station_mutation``, called
    from ``create_child_from_mutation``. The child is a deepcopy of the SOURCE
    scenario, which owns none of these rows, so without this the user's cost inputs
    never reach the simulation.

    ``VehicleType.tco_parameters`` and ``Station.tco_parameters`` are already carried
    by the two functions above, which copy whole rows. That is also why the
    ``battery_type_id`` / ``charging_point_type_id`` of the child point at the
    *mutation's* rows at this point — a cross-scenario reference that would cascade
    into the simulated scenario when the mutation is deleted. Repairing those is the
    second half of this function, so it has to run after ``apply_vehicle_mutation``.

    :param mutation: The MUTATION scenario the wizard wrote to.
    :param child: The SIMULATION scenario, a deepcopy of the SOURCE.
    :param stack: Deepcopy bookkeeping, unused here but kept for signature symmetry
        with the other ``apply_*`` functions.
    """
    child.tco_parameters = deepcopy(mutation.tco_parameters)

    battery_type_map = {}
    for battery_type in BatteryType.objects.filter(scenario=mutation):
        old_id = battery_type.id
        battery_type.id = None
        battery_type.scenario = child
        battery_type.save()
        battery_type_map[old_id] = battery_type.id

    charging_point_type_map = {}
    for charging_point_type in ChargingPointType.objects.filter(scenario=mutation):
        old_id = charging_point_type.id
        charging_point_type.id = None
        charging_point_type.scenario = child
        charging_point_type.save()
        charging_point_type_map[old_id] = charging_point_type.id

    for vehicle_type in VehicleType.objects.filter(scenario=child, battery_type__isnull=False):
        vehicle_type.battery_type_id = battery_type_map.get(vehicle_type.battery_type_id)
        vehicle_type.save(update_fields=["battery_type"])

    for station in Station.objects.filter(scenario=child, charging_point_type__isnull=False):
        station.charging_point_type_id = charging_point_type_map.get(station.charging_point_type_id)
        station.save(update_fields=["charging_point_type"])

    logger.info(
        f"S.ID:{child.id}:Applied TCO mutation from S.ID:{mutation.id} "
        f"({len(battery_type_map)} battery types, "
        f"{len(charging_point_type_map)} charging point types)"
    )


# ---------------------------------------------------------------------------
# Step 3: attach charging point types to the simulated topology
# ---------------------------------------------------------------------------


@atomic()
def attach_charging_point_types(scenario: Scenario) -> None:
    """Point the simulated Areas and Stations at their ChargingPointType.

    Runs after the simulation and before the TCO calculation, because neither target
    exists earlier: Areas are generated by ``run_eflips`` and opportunity charging is
    only visible in the Events the simulation produces.

    Mirrors the assignment rules of ``eflips.impact.utils.complete_fleet`` — depot
    charging points go to every Area with an electric charging Process, opportunity
    charging points to every Station with a ``CHARGING_OPPORTUNITY`` event — but only
    assigns foreign keys. The parameters on the rows themselves were set before the
    simulation and carried over by :func:`apply_tco_mutation`.

    :param scenario: The SIMULATION scenario, after ``apply_depot_strategy``.
    """
    charging_point_types = {
        cpt.name_short: cpt for cpt in ChargingPointType.objects.filter(scenario=scenario)
    }

    depot_cpt = charging_point_types.get(DEPOT_CPT_NAME_SHORT)
    if depot_cpt is not None:
        depot_areas = Area.objects.filter(
            scenario=scenario, processes__electric_power__isnull=False
        ).distinct()
        updated = depot_areas.update(charging_point_type=depot_cpt)
        logger.info(f"S.ID:{scenario.id}:Attached depot charging point to {updated} areas")
    else:
        logger.warning(f"S.ID:{scenario.id}:No depot ChargingPointType to attach")

    opportunity_cpt = charging_point_types.get(OPPORTUNITY_CPT_NAME_SHORT)
    if opportunity_cpt is not None:
        opportunity_station_ids = (
            Event.objects.filter(scenario=scenario, event_type="CHARGING_OPPORTUNITY")
            .exclude(station__isnull=True)
            .values_list("station_id", flat=True)
            .distinct()
        )
        updated = Station.objects.filter(
            scenario=scenario, id__in=list(opportunity_station_ids)
        ).update(charging_point_type=opportunity_cpt)
        logger.info(f"S.ID:{scenario.id}:Attached opportunity charging point to {updated} stations")
    else:
        logger.warning(f"S.ID:{scenario.id}:No opportunity ChargingPointType to attach")


# ---------------------------------------------------------------------------
# Step 4: the calculation
# ---------------------------------------------------------------------------


def get_scaling_factor(scenario: Scenario) -> float:
    """Return the annualisation factor ``365 / simulated_days`` for a scenario.

    eflips-impact derives this from the span between the first and last trip
    *departure*, which understates a single service day: a day whose first bus leaves
    at 20:25 and whose last leaves at 06:26 spans 0.42 days, giving a factor of ~875
    instead of 365. Capital cost per revenue-km scales with the reciprocal of this
    number, so the capex/opex split of the result would be set by that artifact.
    Rounding the span up to whole days keeps a one-day schedule at 365.

    :param scenario: The scenario being calculated.
    :returns: ``365.0 / simulated_days``, with a floor of one day.
    """
    span = Trip.objects.filter(scenario=scenario).aggregate(
        first=Min("departure_time"), last=Max("departure_time")
    )
    if span["first"] is None or span["last"] is None:
        logger.warning(f"S.ID:{scenario.id}:No trips found, assuming a one-day simulation for TCO")
        return 365.0
    days = (span["last"] - span["first"]).total_seconds() / 86_400.0
    return 365.0 / max(1.0, math.ceil(days))


def _write_energy_consumption(scenario: Scenario) -> None:
    """Write the per-vehicle-type average consumption eflips-impact reads.

    ``TCOCalculator`` runs in ``"constant"`` mode and looks for
    ``average_electricity_consumption`` (or ``average_diesel_consumption`` for diesel
    vehicle types) in ``VehicleType.tco_parameters``; a missing value is logged and
    treated as zero, which silently zeroes the energy cost. The value is taken from
    the vehicle type if set, and otherwise derived from the simulated driving events.
    """
    for vehicle_type in VehicleType.objects.filter(scenario=scenario):
        parameters = vehicle_type.tco_parameters or {}

        if vehicle_type.energy_source == EnumEnergySource.DIESEL:
            # No simulated diesel consumption exists; keep whatever was configured.
            if parameters.get("average_diesel_consumption") is None:
                parameters["average_diesel_consumption"] = _tco_vehicle_type_defaults(vehicle_type)[
                    "average_diesel_consumption"
                ]
        elif vehicle_type.consumption is not None:
            parameters["average_electricity_consumption"] = vehicle_type.consumption
        else:
            energy_kwh = sum(
                event.get_energy_delta()
                for event in Event.objects.filter(vehicle_type=vehicle_type, event_type="DRIVING")
            )
            distance = vehicle_type.get_total_distance_km
            if distance:
                # Driving events lose energy, so the delta is negative.
                parameters["average_electricity_consumption"] = -energy_kwh / distance
            else:
                logger.warning(
                    f"S.ID:{scenario.id}:VehicleType {vehicle_type.id} has no distance; "
                    "falling back to the configured consumption for TCO"
                )
                parameters.setdefault(
                    "average_electricity_consumption",
                    _tco_vehicle_type_defaults(vehicle_type)["average_electricity_consumption"],
                )

        vehicle_type.tco_parameters = parameters
        vehicle_type.save(update_fields=["tco_parameters"])


def calculate_tco(scenario: Scenario) -> dict:
    """Run the eflips-impact TCO calculation for a simulated scenario.

    :param scenario: A simulated scenario, after :func:`attach_charging_point_types`.
    :returns: ``{cost_category: EUR per revenue-km}``, the flat shape stored in
        ``Scenario.tco_result`` and read by the result page.
    """
    from ebustoolbox.tasks import create_db_url  # avoids a circular import

    _ensure_scenario_parameters(scenario)
    _write_energy_consumption(scenario)

    result = eflips_calculate_tco(
        scenario.id,
        database_url=create_db_url(),
        scaling_factor=get_scaling_factor(scenario),
    )
    return tco_result_to_dict(result)


def tco_result_to_dict(result) -> dict:
    """Flatten a :class:`eflips.impact.tco.TCOResult` for storage and the frontend.

    The result page iterates ``Object.keys(tco_result)`` and treats every value as a
    bar segment, so the stored dict has to stay a flat category-to-number mapping.

    :param result: The ``TCOResult`` returned by eflips-impact.
    :returns: ``{category name: EUR per revenue-km}``.
    """
    return {category.name: value for category, value in result.tco_by_type_per_revenue_km.items()}
