# Generated by Django 4.2.1 on 2023-06-23 11:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EbusToolbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.TextField(blank=True)),
                ('output_directory', models.TextField(blank=True, default='ebustoolbox/static/data/sim_outputs/')),
                ('input_schedule', models.FileField(blank=True, default='data/examples/trips_example.csv', upload_to='uploads/')),
                ('electrified_stations', models.FileField(blank=True, default='data/examples/electrified_stations.json', upload_to='uploads/')),
                ('vehicle_types', models.FileField(blank=True, default='data/examples/vehicle_types.json', upload_to='uploads/')),
                ('station_data_path', models.FileField(blank=True, default='data/examples/all_stations.csv', upload_to='uploads/')),
                ('outside_temperature_over_day_path', models.FileField(blank=True, default='data/examples/default_temp_winter.csv', upload_to='uploads/')),
                ('level_of_loading_over_day_path', models.FileField(blank=True, default='data/examples/default_level_of_loading_over_day.csv', upload_to='uploads/')),
                ('cost_parameters_file', models.FileField(blank=True, default='data/examples/cost_params.json', upload_to='uploads/')),
                ('gc_power_opps', models.DecimalField(decimal_places=2, default=100000, max_digits=10)),
                ('gc_power_deps', models.DecimalField(decimal_places=2, default=100000, max_digits=10)),
                ('cs_power_opps', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('cs_power_deps_depb', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('cs_power_deps_oppb', models.DecimalField(decimal_places=2, default=150, max_digits=10)),
                ('desired_soc_deps', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('desired_soc_opps', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('min_recharge_deps_oppb', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('min_recharge_deps_depb', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('min_charging_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('default_buffer_time_opps', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EbusToolboxTimeseries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=None)),
                ('soc', models.FloatField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('soc', models.FloatField(null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(default='ImaBusStop')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario')),
            ],
        ),
    ]
