# Generated by Django 4.2.2 on 2023-07-03 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EbusToolbox',
        ),
        migrations.DeleteModel(
            name='EbusToolboxTimeseries',
        ),
        migrations.DeleteModel(
            name='TaskRun',
        ),
        migrations.RemoveField(
            model_name='vehicleproperties',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='vehicleproperties',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='busstop',
            name='charge_type',
            field=models.CharField(choices=[('opps', 'opps'), ('deps', 'deps')], default='deps', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busstop',
            name='voltage_level',
            field=models.CharField(choices=[('HV', 'HV'), ('HV/MV', 'HV/MV'), ('MV', 'MV'), ('MV/LV', 'MV/LV'), ('LV', 'LV')], default='MV', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenario',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenario',
            name='finished',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='options',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenario',
            name='task_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='name',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='id',
        ),
        migrations.AddField(
            model_name='scenario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='VehicleProperties',
        ),
    ]
