# Generated by Django 4.2.2 on 2023-07-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0002_delete_ebustoolbox_delete_ebustoolboxtimeseries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='charge_type',
            field=models.CharField(choices=[('oppb', 'Opportunity'), ('depb', 'Depot')], max_length=4),
        ),
    ]
