# Generated by Django 4.2.2 on 2023-07-05 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0003_alter_busstop_charge_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario')),
            ],
        ),
    ]
