# Generated by Django 4.2.2 on 2023-07-05 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0004_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstop',
            name='scenario',
        ),
        migrations.AddField(
            model_name='busstop',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario'),
        ),
    ]
