# Generated by Django 4.2.2 on 2023-07-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0005_alter_busstop_scenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='options',
            field=models.JSONField(default=dict),
        ),
    ]
