# Generated by Django 4.2.2 on 2023-08-01 07:50

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import ebustoolbox.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0006_alter_scenario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbusToolboxTimeseries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=None)),
                ('soc', models.FloatField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='deps_charging_power',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='opps_charging_power',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='charge_type',
            field=models.CharField(choices=[('oppb', 'Opportunity'), ('depb', 'Depot')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='voltage_level',
            field=models.CharField(choices=[('HV', 'HV'), ('HV/MV', 'HV/MV'), ('MV', 'MV'), ('MV/LV', 'MV/LV'), ('LV', 'LV')], max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flex_charging', models.BooleanField()),
                ('battery_capacity', models.FloatField()),
                ('charging_efficiency', models.FloatField(default=0.95)),
                ('minimum_charging_power', models.FloatField(default=0)),
                ('charging_curve', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2), size=None)),
                ('v2g_curve', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2), size=None)),
                ('v2g', models.BooleanField(default=False)),
                ('consumption', models.FloatField(default=None, null=True)),
                ('length', models.FloatField(default=None, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario')),
                ('vehicle_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.vehicleclass')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('soc', models.FloatField(null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.vehicletype'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('distance', models.FloatField()),
                ('line', models.CharField(blank=True, max_length=100, null=True)),
                ('temperature', models.FloatField(default=None, null=True)),
                ('level_of_loading', models.FloatField(default=None, null=True)),
                ('arrival_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_arrival_set', to='ebustoolbox.busstop')),
                ('departure_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_departure_set', to='ebustoolbox.busstop')),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.rotation')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326)),
                ('name', models.TextField()),
                ('is_electrified', models.BooleanField(default=False)),
                ('charge_type', models.CharField(choices=[('oppb', 'Opportunity'), ('depb', 'Depot')], max_length=4, null=True)),
                ('voltage_level', models.CharField(choices=[('HV', 'HV'), ('HV/MV', 'HV/MV'), ('MV', 'MV'), ('MV/LV', 'MV/LV'), ('LV', 'LV')], max_length=5, null=True)),
                ('amount_charging_places', models.IntegerField(default=0, null=True)),
                ('power_per_charger', models.FloatField(default=None, null=True)),
                ('total_power', models.FloatField(default=None, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario')),
            ],
        ),
        migrations.AddField(
            model_name='rotation',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario'),
        ),
        migrations.AddField(
            model_name='rotation',
            name='vehicle_class',
            field=models.ForeignKey(default=ebustoolbox.models.VehicleClass.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='ebustoolbox.vehicleclass'),
        ),
    ]
