# Generated by Django 4.2.2 on 2023-08-02 13:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0007_ebustoolboxtimeseries_rotation_vehicle_vehicleclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='v2g_curve',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2), null=True, size=None),
        ),
    ]
