# Generated by Django 4.2.2 on 2023-08-02 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0008_alter_vehicletype_v2g_curve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='arrival_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_arrival_set', to='ebustoolbox.station'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_departure_set', to='ebustoolbox.station'),
        ),
        migrations.DeleteModel(
            name='BusStop',
        ),
    ]
