# Generated by Django 4.2.3 on 2023-08-15 12:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0009_alter_trip_arrival_stop_alter_trip_departure_stop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='charging_curve',
            field=models.JSONField(verbose_name=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2)),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='v2g_curve',
            field=models.JSONField(null=True, verbose_name=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2)),
        ),
    ]
