# Generated by Django 4.2.2 on 2023-08-16 08:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "ebustoolbox",
            "0009_alter_trip_arrival_stop_alter_trip_departure_stop_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scenario",
            name="deps_charging_power",
        ),
        migrations.RemoveField(
            model_name="scenario",
            name="opps_charging_power",
        ),
    ]
