# Generated by Django 4.2.4 on 2023-09-21 11:17

from django.db import migrations, models
import django.db.models.deletion
import ebustoolbox.models

class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0010_remove_scenario_deps_charging_power_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleclass",
            name="scenario",
            field=models.ForeignKey(
                default=ebustoolbox.models.Scenario.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
            ),
        ),
        migrations.RemoveField(
            model_name="vehicletype",
            name="vehicle_class",
        ),
    ]
