# Generated by Django 4.2.4 on 2023-09-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0010_remove_scenario_deps_charging_power_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicletype",
            name="name_short",
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
        migrations.AlterField(
            model_name="station",
            name="charge_type",
            field=models.CharField(
                choices=[("opps", "Opportunity"), ("deps", "Depot")], max_length=4, null=True
            ),
        ),
    ]
