# Generated by Django 4.2.4 on 2023-09-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0011_vehicletype_name_short_alter_station_charge_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="charge_type",
            field=models.CharField(
                choices=[("oppb", "Opportunity"), ("depb", "Depot")], max_length=4, null=True
            ),
        ),
    ]
