# Generated by Django 4.2.4 on 2023-09-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0011_vehicleclass_scenario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicletype",
            name="name_short",
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="vehicle_class",
            field=models.ManyToManyField(to="ebustoolbox.vehicleclass"),
        ),
    ]

