# Generated by Django 4.2.4 on 2023-09-06 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0012_alter_station_charge_type_auxiliaryfloattable"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuxiliaryFloatTable",
        ),
    ]
