# Generated by Django 4.2.4 on 2023-09-21 13:22

from django.db import migrations, models
import django.db.models.deletion
import ebustoolbox.models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0012_vehicletype_name_short"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleclass",
            name="scenario",
            field=models.ForeignKey(
                default=ebustoolbox.models.Scenario.get_default_pk,
                on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
            ),
        ),
    ]
