# Generated by Django 4.2.4 on 2023-10-06 12:28

from django.db import migrations, models
import django.db.models.deletion
import ebustoolbox.models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0013_alter_vehicleclass_scenario"),
    ]

    operations = [
        migrations.AddField(
            model_name="rotation",
            name="is_depot_rotation",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="rotation",
            name="vehicle",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="ebustoolbox.vehicle",
            ),
        ),
    ]
