# Generated by Django 4.2.4 on 2023-10-06 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0014_rotation_is_depot_rotation_rotation_vehicle_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="scenario",
        ),
    ]
