# Generated by Django 4.2.7 on 2023-11-20 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0015_remove_vehicle_scenario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rotation',
            name='vehicle_class',
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='vehicle_class',
        ),
        migrations.AddField(
            model_name='rotation',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.vehicletype'),
        ),
        migrations.AddField(
            model_name='trip',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario'),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario'),
        ),
        migrations.AlterField(
            model_name='station',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario'),
        ),
        migrations.AlterField(
            model_name='vehicleproperties',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario'),
        ),
    ]
