# Generated by Django 4.2.7 on 2023-11-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0016_remove_rotation_vehicle_class_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleClass',
        ),
    ]
