# Generated by Django 4.2.7 on 2023-11-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0017_delete_vehicleclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EbusToolboxTimeseries',
        ),
        migrations.RenameField(
            model_name='rotation',
            old_name='is_depot_rotation',
            new_name='allow_opportunity_charging',
        ),
        migrations.AddField(
            model_name='trip',
            name='empty',
            field=models.BooleanField(default=False),
        ),
    ]
