# Generated by Django 4.2.7 on 2023-11-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0017_delete_vehicleclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EbusToolboxTimeseries',
        ),
    ]
