# Generated by Django 4.2.7 on 2023-11-20 13:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0018_delete_ebustoolboxtimeseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(dim=3, null=True, srid=4326)),
                ('scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=None, null=True)),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.route')),
                ('scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.route'),
        ),
    ]
