# Generated by Django 4.2.7 on 2023-11-20 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0019_route_line_trip_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.station')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.trip')),
            ],
        ),
    ]
