# Generated by Django 4.2.7 on 2023-11-20 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0020_stoptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebustoolbox.scenario'),
        ),
    ]
