# Generated by Django 4.2.7 on 2023-11-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0021_scenario_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicletype',
            old_name='flex_charging',
            new_name='opportunity_charging_capable',
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='v2g',
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='battery_reserve_capacity',
            field=models.FloatField(default=0),
        ),
    ]
