# Generated by Django 4.2.7 on 2023-11-23 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0022_rename_flex_charging_vehicletype_opportunity_charging_capable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='options',
            new_name='simba_options',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='total_power',
            new_name='power_total',
        ),
        migrations.RenameField(
            model_name='stoptime',
            old_name='duration',
            new_name='dwell_duration',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='arrival_stop',
            new_name='arrival_station',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='departure_stop',
            new_name='departure_station',
        ),
        migrations.RenameField(
            model_name='vehicletype',
            old_name='length',
            new_name='length_m',
        ),
        migrations.RemoveField(
            model_name='line',
            name='route',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='empty',
        ),
        migrations.AddField(
            model_name='line',
            name='name_short',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='headsign',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.line'),
        ),
        migrations.AddField(
            model_name='station',
            name='name_short',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stoptime',
            name='elapsed_distance_m',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stoptime',
            name='ordinal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='type',
            field=models.CharField(choices=[('empty', 'Empty Trip'), ('passenger', 'Passenger Trip')], default='passenger', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name_short',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='empty_mass_kg',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='width_m',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='charge_type',
            field=models.CharField(choices=[('depb', 'Depot'), ('oppb', 'Opportunity')], default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='voltage_level',
            field=models.CharField(choices=[('HV', 'Voltage Hv'), ('HV/MV', 'Voltage Hv Mv'), ('MV', 'Voltage Mv'), ('MV/LV', 'Voltage Mv Lv'), ('LV', 'Voltage Lv')], default=None, max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='BatteryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_mass_kg_per_kwh', models.FloatField(blank=True, null=True)),
                ('chemistry', models.JSONField(default=dict)),
                ('scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario')),
            ],
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='battery_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.batterytype'),
        ),
    ]
