# Generated by Django 4.2.7 on 2023-11-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0023_rename_options_scenario_simba_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='allowed_mass_kg',
            field=models.FloatField(default=None, null=True),
        ),
    ]
