# Generated by Django 4.2.7 on 2023-11-23 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0024_vehicletype_allowed_mass_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subloc_no', models.IntegerField(blank=True, null=True)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('soc_start', models.FloatField()),
                ('soc_end', models.FloatField()),
                ('timeseries', models.JSONField(default=dict)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.area')),
                ('scenario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.station')),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.trip')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.vehicle')),
                ('vehicle_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.vehicletype')),
            ],
        ),
    ]
