# Generated by Django 4.2.7 on 2023-11-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0025_area_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='line',
        ),
    ]
