# Generated by Django 4.2.7 on 2023-11-24 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0026_remove_trip_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.line'),
        ),
    ]
