# Generated by Django 4.2.7 on 2023-11-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0027_trip_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='name_short',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
