# Generated by Django 4.2.7 on 2024-01-03 17:37

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0028_route_name_route_name_short"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssocPlanProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ordinal", models.IntegerField()),
            ],
            options={
                "db_table": "AssocPlanProcess",
            },
        ),
        migrations.CreateModel(
            name="AssocVehicleTypeVehicleClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "db_table": "AssocVehicleTypeVehicleClass",
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
            ],
            options={
                "db_table": "Plan",
            },
        ),
        migrations.RenameField(
            model_name="trip",
            old_name="level_of_loading",
            new_name="loaded_mass",
        ),
        migrations.RenameField(
            model_name="vehicletype",
            old_name="allowed_mass_kg",
            new_name="allowed_mass",
        ),
        migrations.RenameField(
            model_name="vehicletype",
            old_name="battery_reserve_capacity",
            new_name="battery_capacity_reserve",
        ),
        migrations.RenameField(
            model_name="vehicletype",
            old_name="empty_mass_kg",
            new_name="empty_mass",
        ),
        migrations.RenameField(
            model_name="vehicletype",
            old_name="length_m",
            new_name="length",
        ),
        migrations.RenameField(
            model_name="vehicletype",
            old_name="width_m",
            new_name="width",
        ),
        migrations.RemoveField(
            model_name="batterytype",
            name="specific_mass_kg_per_kwh",
        ),
        migrations.RemoveField(
            model_name="stoptime",
            name="elapsed_distance_m",
        ),
        migrations.RemoveField(
            model_name="stoptime",
            name="ordinal",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="arrival_station",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="departure_station",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="distance",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="line",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="temperature",
        ),
        migrations.AddField(
            model_name="area",
            name="area_type",
            field=models.CharField(
                choices=[
                    ("DIRECT_ONESIDE", "Direct Oneside"),
                    ("DIRECT_TWOSIDE", "Direct Twoside"),
                    ("LINE", "Linear"),
                ],
                default=None,
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="capacity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="area",
            name="name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="area",
            name="name_short",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="area",
            name="row_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="area",
            name="scenario",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="area",
            name="vehicle_type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebustoolbox.vehicletype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="batterytype",
            name="specific_mass",
            field=models.FloatField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("DRIVING", "Driving"),
                    ("CHARGING_OPPORTUNITY", "Charging Opportunity"),
                    ("CHARGING_DEPOT", "Charging Depot"),
                    ("SERVICE", "Sercvice"),
                    ("STANDBY_DEPARTURE", "Standby Departure"),
                    ("PRECONDITIONING", "Preconditioning"),
                ],
                default=None,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="arrival_station",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_arrival_set",
                to="ebustoolbox.station",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="route",
            name="departure_station",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_departure_set",
                to="ebustoolbox.station",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="route",
            name="distance",
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name="scenario",
            name="eflips_depot_options",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name="scenario",
            name="name_short",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="height",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="batterytype",
            name="scenario",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="timeseries",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="vehicle_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.vehicletype"
            ),
        ),
        migrations.AlterField(
            model_name="line",
            name="name",
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name="line",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
            ),
        ),
        migrations.AlterField(
            model_name="rotation",
            name="allow_opportunity_charging",
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name="rotation",
            name="name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="rotation",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
            ),
        ),
        migrations.AlterField(
            model_name="rotation",
            name="vehicle_type",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebustoolbox.vehicletype",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="name",
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name="route",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
            ),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebustoolbox.scenario",
            ),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="simba_options",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="task_id",
            field=models.UUIDField(default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="name_short",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="voltage_level",
            field=models.CharField(
                choices=[
                    ("HV", "Voltage Hv"),
                    ("HV_MV", "Voltage Hv Mv"),
                    ("MV", "Voltage Mv"),
                    ("MV_LV", "Voltage Mv Lv"),
                    ("LV", "Voltage Lv"),
                ],
                default=None,
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stoptime",
            name="dwell_duration",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name="stoptime",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.route"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="type",
            field=models.CharField(
                choices=[("EMPTY", "Empty Trip"), ("PASSENGER", "Passenger Trip")],
                default="PASSENGER",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="name_short",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebustoolbox.vehicletype",
            ),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="name_short",
            field=models.TextField(default=models.TextField(), null=True),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
            ),
        ),
        migrations.AlterModelTable(
            name="area",
            table="Area",
        ),
        migrations.AlterModelTable(
            name="batterytype",
            table="BatteryType",
        ),
        migrations.AlterModelTable(
            name="event",
            table="Event",
        ),
        migrations.AlterModelTable(
            name="line",
            table="Line",
        ),
        migrations.AlterModelTable(
            name="rotation",
            table="Rotation",
        ),
        migrations.AlterModelTable(
            name="route",
            table="Route",
        ),
        migrations.AlterModelTable(
            name="scenario",
            table="Scenario",
        ),
        migrations.AlterModelTable(
            name="station",
            table="Station",
        ),
        migrations.AlterModelTable(
            name="stoptime",
            table="StopTime",
        ),
        migrations.AlterModelTable(
            name="trip",
            table="Trip",
        ),
        migrations.AlterModelTable(
            name="vehicle",
            table="Vehicle",
        ),
        migrations.AlterModelTable(
            name="vehicletype",
            table="VehicleType",
        ),
        migrations.CreateModel(
            name="VehicleClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("name_short", models.TextField(blank=True, null=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
                    ),
                ),
                (
                    "vehicle_types",
                    models.ManyToManyField(
                        through="ebustoolbox.AssocVehicleTypeVehicleClass",
                        to="ebustoolbox.vehicletype",
                    ),
                ),
            ],
            options={
                "db_table": "VehicleClass",
            },
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("name_short", models.TextField(null=True)),
                ("duration", models.DurationField(null=True)),
                ("electric_power", models.FloatField(null=True)),
                ("dispatchable", models.BooleanField()),
                ("availability", models.JSONField(default=dict, null=True)),
                (
                    "plans",
                    models.ManyToManyField(
                        through="ebustoolbox.AssocPlanProcess", to="ebustoolbox.plan"
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
                    ),
                ),
            ],
            options={
                "db_table": "Process",
            },
        ),
        migrations.AddField(
            model_name="plan",
            name="processes",
            field=models.ManyToManyField(
                through="ebustoolbox.AssocPlanProcess", to="ebustoolbox.process"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
            ),
        ),
        migrations.CreateModel(
            name="Depot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("name_short", models.TextField(blank=True, null=True)),
                (
                    "default_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.plan"
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
                    ),
                ),
            ],
            options={
                "db_table": "Depot",
            },
        ),
        migrations.AddField(
            model_name="assocvehicletypevehicleclass",
            name="vehicle_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.vehicleclass"
            ),
        ),
        migrations.AddField(
            model_name="assocvehicletypevehicleclass",
            name="vehicle_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.vehicletype"
            ),
        ),
        migrations.CreateModel(
            name="AssocRouteStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("elapsed_distance", models.FloatField()),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(dim=3, null=True, srid=4326),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.route"
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.station"
                    ),
                ),
            ],
            options={
                "db_table": "AssocRouteStation",
                "ordering": ["elapsed_distance"],
            },
        ),
        migrations.AddField(
            model_name="assocplanprocess",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.plan"
            ),
        ),
        migrations.AddField(
            model_name="assocplanprocess",
            name="process",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.process"
            ),
        ),
        migrations.AddField(
            model_name="assocplanprocess",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
            ),
        ),
        migrations.CreateModel(
            name="AssocAreaProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.area"
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.process"
                    ),
                ),
            ],
            options={
                "db_table": "AssocAreaProcess",
            },
        ),
        migrations.AddField(
            model_name="area",
            name="depot",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.depot"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="area",
            name="processes",
            field=models.ManyToManyField(
                through="ebustoolbox.AssocAreaProcess", to="ebustoolbox.process"
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="stations",
            field=models.ManyToManyField(
                through="ebustoolbox.AssocRouteStation", to="ebustoolbox.station"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="stations",
            field=models.ManyToManyField(
                through="ebustoolbox.AssocRouteStation", to="ebustoolbox.route"
            ),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="vehicle_classes",
            field=models.ManyToManyField(
                through="ebustoolbox.AssocVehicleTypeVehicleClass", to="ebustoolbox.vehicleclass"
            ),
        ),
    ]
