# Generated by Django 4.2.7 on 2023-12-11 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0028_route_name_route_name_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.scenario'),
        ),
    ]
