# Generated by Django 4.2.7 on 2024-01-05 15:17

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0031_assocplanprocess_assocvehicletypevehicleclass_plan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Temperatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("use_only_time", models.BooleanField(default=True)),
                (
                    "datetimes",
                    models.JSONField(
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("data", models.JSONField(default=list, null=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
                    ),
                ),
            ],
            options={
                "db_table": "Temperatures",
            },
        ),
    ]
