# Generated by Django 4.2.7 on 2024-01-25 12:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0032_temperatures"),
    ]



    operations = [
        migrations.RemoveField(
            model_name="temperatures",
            name="data",
        ),

        migrations.AddField(
            model_name="temperatures",
            name="data",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), default=list, size=None
            ),
        ),
        migrations.RemoveField(
            model_name="temperatures",
            name="datetimes",
        ),

        migrations.AddField(
            model_name="temperatures",
            name="datetimes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateTimeField(), default=list, size=None
            ),
        ),
    ]
