# Generated by Django 4.2.9 on 2024-02-01 13:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0033_alter_temperatures_data_alter_temperatures_datetimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(dim=3, null=True, srid=4326),
        ),
    ]
