# Generated by Django 4.2.7 on 2024-01-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0029_alter_scenario_parent'),
        ('ebustoolbox', '0033_alter_temperatures_data_alter_temperatures_datetimes'),
    ]

    operations = [
    ]
