# Generated by Django 4.2.7 on 2024-01-31 14:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0034_merge_20240131_1438'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='assocroutestation',
            managers=[
                ('vector_tiles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='route',
            managers=[
                ('vector_tiles', django.db.models.manager.Manager()),
            ],
        ),
    ]
