# Generated by Django 4.2.9 on 2024-02-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0034_alter_station_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('DRIVING', 'Driving'), ('CHARGING_OPPORTUNITY', 'Charging Opportunity'), ('CHARGING_DEPOT', 'Charging Depot'), ('SERVICE', 'Service'), ('STANDBY_DEPARTURE', 'Standby Departure'), ('PRECONDITIONING', 'Preconditioning')], default=None, max_length=20),
        ),
    ]
