# Generated by Django 4.2.9 on 2024-02-05 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0035_alter_event_event_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VehicleProperties",
        ),
    ]
