# Generated by Django 4.2.7 on 2024-01-31 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0035_alter_assocroutestation_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='assocroutestation',
            managers=[
            ],
        ),
    ]
