# Generated by Django 4.2.9 on 2024-02-06 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0036_delete_vehicleproperties"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="type",
            new_name="trip_type",
        ),
    ]
