# Generated by Django 4.2.7 on 2024-02-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0036_alter_assocroutestation_managers'),
        ('ebustoolbox', '0037_rename_type_trip_trip_type'),
    ]

    operations = [
    ]
