# Generated by Django 4.2.9 on 2024-02-07 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ebustoolbox", "0037_rename_type_trip_trip_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scenario",
            name="users",
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("scenarios", models.ManyToManyField(to="ebustoolbox.scenario")),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
