# Generated by Django 5.0.2 on 2024-02-27 18:28

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0038_remove_scenario_users_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='created',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
