# Generated by Django 4.2.10 on 2024-02-22 11:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0038_remove_scenario_users_usergroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("columns", models.JSONField(verbose_name=[])),
                (
                    "data_points",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.FloatField(), size=None
                        ),
                        size=None,
                    ),
                ),
                (
                    "values",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=None
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ebustoolbox.scenario",
                    ),
                ),
                (
                    "vehicle_class",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ebustoolbox.vehicleclass",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="consumption",
            constraint=models.UniqueConstraint(
                fields=("name", "scenario"), name="unique_with_scenario"
            ),
        ),
        migrations.AddConstraint(
            model_name="consumption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scenario", None)),
                fields=("name",),
                name="unique_without_scenario",
            ),
        ),
    ]
