# Generated by Django 4.2.10 on 2024-02-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0038_merge_20240206_1338'),
        ('ebustoolbox', '0038_remove_scenario_users_usergroup'),
    ]

    operations = [
    ]
