# Generated by Django 4.2.10 on 2024-03-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0039_consumption_consumption_unique_with_scenario_and_more'),
        ('ebustoolbox', '0039_merge_20240226_0916'),
    ]

    operations = [
    ]
