# Generated by Django 4.2.10 on 2024-02-07 14:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0039_consumption"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consumption",
            old_name="data",
            new_name="data_points",
        ),
        migrations.AddField(
            model_name="consumption",
            name="values",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), default=[1.0], size=None
            ),
            preserve_default=False,
        ),
    ]
