# Generated by Django 4.2.10 on 2024-04-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0039_consumption_consumption_unique_with_scenario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='station',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.CASCADE, to='ebustoolbox.station'),
            preserve_default=False,
        ),
    ]
