# Generated by Django 4.2.10 on 2024-03-21 10:08

from django.db import migrations, models
import django.db.models.deletion
from ebustoolbox.default_scenario import set_default_scenario

class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0040_depot_station"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("_singleton", models.BooleanField(default=True, editable=False, unique=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
                    ),
                ),
            ],
        ),
        migrations.RunPython(set_default_scenario, lambda app, shema_editor: ()),

    ]
