# Generated by Django 4.2.10 on 2024-02-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0040_rename_data_consumption_data_points_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="consumption",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="consumption",
            constraint=models.UniqueConstraint(
                fields=("name", "scenario"), name="unique_with_scenario"
            ),
        ),
        migrations.AddConstraint(
            model_name="consumption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scenario", None)),
                fields=("name",),
                name="unique_without_scenario",
            ),
        ),
    ]
