# Generated by Django 4.2.10 on 2024-02-12 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0040_alter_consumption_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicletype",
            name="consumption_table",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.consumption"
            ),
        ),
    ]
