# Generated by Django 5.0.4 on 2024-04-17 08:32

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0041_defaultscenario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
    ]
