# Generated by Django 5.0.4 on 2024-04-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0042_alter_scenario_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batterytype",
            name="chemistry",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="battery_capacity_reserve",
            field=models.FloatField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="charging_efficiency",
            field=models.FloatField(db_default=0.95, default=0.95),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="minimum_charging_power",
            field=models.FloatField(db_default=0, default=0),
        ),
    ]
