# Generated by Django 5.0.4 on 2024-05-13 12:09

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0044_update_defaultscenario"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="route",
            managers=[
                ("vector_tiles", django.db.models.manager.Manager()),
            ],
        ),
    ]
