# Generated by Django 5.0.4 on 2024-05-02 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0039_merge_20240226_0916"),
        ("ebustoolbox", "0044_update_defaultscenario"),
    ]

    operations = []
