# Generated by Django 5.0.6 on 2024-06-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0045_alter_route_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="route",
            managers=[],
        ),
    ]
