# Generated by Django 5.0.6 on 2024-07-02 08:57

from django.db import migrations
from ebustoolbox.default_scenario import set_default_scenario


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0046_alter_route_managers"),
    ]

    operations = [
        migrations.RunPython(set_default_scenario, lambda app, schema_editor: ()),
    ]
