# Generated by Django 5.0.6 on 2024-07-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0047_alter_default_scenario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rotation",
            name="allow_opportunity_charging",
            field=models.BooleanField(default=True),
        ),
    ]
