# Generated by Django 5.0.6 on 2024-07-17 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0047_alter_default_scenario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="vehicle_type",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.vehicletype"
            ),
        ),
    ]
