# Generated by Django 5.0.6 on 2024-09-05 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0047_alter_default_scenario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="area",
            name="row_count",
        ),
        migrations.AlterField(
            model_name="area",
            name="vehicle_type",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.vehicletype"
            ),
        ),
        migrations.AlterField(
            model_name="rotation",
            name="allow_opportunity_charging",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name="consumption",
            table="ConsumptionLut",
        ),
    ]
