# Generated by Django 5.0.6 on 2024-08-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0048_alter_area_vehicle_type"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="consumption",
            table="Consumption",
        ),
    ]
