# Generated by Django 5.0.6 on 2024-07-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0048_alter_area_vehicle_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="area",
            name="row_count",
        ),
    ]
