# Generated by Django 5.0.6 on 2024-08-15 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0048_alter_rotation_allow_opportunity_charging"),
        ("ebustoolbox", "0049_remove_area_row_count"),
    ]

    operations = []
