# Generated by Django 5.0.6 on 2024-09-17 11:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0050_merge_20240815_0743"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicletype",
            name="battery_capacity",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000000),
                ]
            ),
        ),
        migrations.CreateModel(
            name="DepotMutation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mutated_original_depot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mutateddepot",
                        to="ebustoolbox.depot",
                    ),
                ),
                (
                    "original_depot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="originaldepot",
                        to="ebustoolbox.depot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepotSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("depots", models.ManyToManyField(to="ebustoolbox.station")),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ElectrificationOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "gc_power_opps",
                    models.PositiveIntegerField(
                        default=5000,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                    ),
                ),
                (
                    "cs_power_opps",
                    models.PositiveIntegerField(
                        default=150,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                    ),
                ),
                (
                    "amount_charging_places",
                    models.PositiveIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
                ("station_optimization", models.BooleanField()),
                ("electrified_stations", models.ManyToManyField(to="ebustoolbox.station")),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimulationRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StationMutation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mutated_original_station",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mutatedstation",
                        to="ebustoolbox.station",
                    ),
                ),
                (
                    "original_station",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="originalstation",
                        to="ebustoolbox.station",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleTypeMutation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mutated_vehicle_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mutatedvehicletype",
                        to="ebustoolbox.vehicletype",
                    ),
                ),
                (
                    "original_vehicle_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="originalvehicletype",
                        to="ebustoolbox.vehicletype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleTypeSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "default_vehicle_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formdefaultvehicletype",
                        to="ebustoolbox.vehicletype",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formvehicletype",
                        to="ebustoolbox.vehicletype",
                    ),
                ),
            ],
        ),
    ]
