# Generated by Django 5.0.6 on 2024-09-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0050_merge_20240815_0743'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consumption',
            table='ConsumptionLut',
        ),
    ]
