# Generated by Django 5.0.6 on 2024-09-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0051_alter_consumption_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="temperatures",
            old_name="use_only_time",
            new_name="is_one_repeating_day",
        ),
        migrations.RemoveField(
            model_name="temperatures",
            name="name",
        ),
    ]
