# Generated by Django 5.1.6 on 2025-03-03 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0052_alter_vehicletype_battery_capacity_depotmutation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.TextField(default="", null=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
                    ),
                ),
            ],
        ),
    ]
