# Generated by Django 5.1.6 on 2025-03-04 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0053_scenariodescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationrange",
            name="temperature",
            field=models.FloatField(
                default=20,
                validators=[
                    django.core.validators.MinValueValidator(-20),
                    django.core.validators.MaxValueValidator(40),
                ],
            ),
            preserve_default=False,
        ),
    ]
