# Generated by Django 5.1.6 on 2025-03-07 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0054_simulationrange_temperature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationrange",
            name="temperature",
            field=models.FloatField(
                default=-10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-20),
                    django.core.validators.MaxValueValidator(40),
                ],
            ),
        ),
    ]
