# Generated by Django 5.1.6 on 2025-03-11 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0057_stationelectrificationexclusions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stationelectrificationexclusions",
            old_name="Station",
            new_name="station",
        ),
    ]
