# Generated by Django 5.1.6 on 2025-03-19 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0058_rename_station_stationelectrificationexclusions_station"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioWizardOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "station_calculation_mode",
                    models.CharField(
                        choices=[
                            ("automatic", "Automatic"),
                            ("constant_power", "Constant Power"),
                            ("manual", "Manual"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "tco_calculation_mode",
                    models.CharField(
                        choices=[
                            ("automatic", "Automatic"),
                            ("constant_power", "Constant Power"),
                            ("manual", "Manual"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "lca_calculation_mode",
                    models.CharField(
                        choices=[
                            ("automatic", "Automatic"),
                            ("constant_power", "Constant Power"),
                            ("manual", "Manual"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
                    ),
                ),
            ],
        ),
    ]
