# Generated by Django 5.1.6 on 2025-03-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0059_scenariowizardoptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationrange",
            name="end",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="simulationrange",
            name="start",
            field=models.DateTimeField(null=True),
        ),
    ]
