# Generated by Django 5.1.6 on 2025-03-20 11:41

from django.db import migrations

from ebustoolbox.default_scenario import set_default_scenario


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0060_alter_simulationrange_end_and_more"),
    ]

    operations = [
        migrations.RunPython(set_default_scenario, lambda app, schema_editor: ()),
    ]
