# Generated by Django 5.1.6 on 2025-04-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0061_enforce_default_scenario_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scenario",
            name="scenario_type",
            field=models.CharField(
                choices=[
                    ("SOURCE", "Source"),
                    ("MUTATION", "Mutation"),
                    ("SIMULATION", "Simulation"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="is_electrifiable",
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name="ScenarioDescription",
        ),
    ]
