# Generated by Django 5.1.6 on 2025-04-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0062_scenario_description_scenario_scenario_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StationElectrificationExclusions",
        ),
    ]
