# Generated by Django 5.1.6 on 2025-04-14 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0063_delete_stationelectrificationexclusions"),
    ]

    operations = [
        migrations.AddField(
            model_name="depotmutation",
            name="scenario",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
            ),
        ),
        migrations.AddField(
            model_name="stationmutation",
            name="scenario",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
            ),
        ),
        migrations.AddField(
            model_name="vehicletypemutation",
            name="scenario",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
            ),
        ),
    ]
