# Generated by Django 5.1.6 on 2025-05-13 13:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0064_depotmutation_scenario_stationmutation_scenario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="bounding_box",
            field=django.contrib.gis.db.models.fields.PolygonField(
                default=None, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="row_count",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="depot",
            name="bounding_box",
            field=django.contrib.gis.db.models.fields.PolygonField(
                default=None, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="area_type",
            field=models.CharField(
                choices=[
                    ("DIRECT_ONESIDE", "Direct Oneside"),
                    ("DIRECT_TWOSIDE", "Direct Twoside"),
                    ("LINE", "Linear"),
                ],
                default=None,
                max_length=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="batterytype",
            name="chemistry",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="consumption",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
            ),
        ),
        migrations.AlterField(
            model_name="consumption",
            name="vehicle_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.vehicleclass"
            ),
        ),
    ]
