# Generated by Django 5.1.6 on 2025-05-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0065_area_bounding_box_area_row_count_depot_bounding_box_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="consumption",
            name="unique_with_scenario",
        ),
        migrations.RemoveConstraint(
            model_name="consumption",
            name="unique_without_scenario",
        ),
        migrations.AlterField(
            model_name="consumption",
            name="columns",
            field=models.JSONField(default=list),
        ),
    ]
