# Generated by Django 5.1.6 on 2025-07-30 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0066_remove_consumption_unique_with_scenario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="scenario_type",
            field=models.CharField(
                choices=[
                    ("source", "Source"),
                    ("muation", "Mutation"),
                    ("simulation", "Simulation"),
                ],
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SimulationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sim_type",
                    models.CharField(
                        choices=[("default", "Default"), ("sizing", "Sizing")], max_length=20
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
                    ),
                ),
            ],
        ),
    ]
