# Generated by Django 5.1.6 on 2025-05-30 09:53

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0066_remove_consumption_unique_with_scenario_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("sender", models.CharField(max_length=255)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("error", "Error"),
                            ("warning", "Warning"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(max_length=20)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
                    ),
                ),
            ],
        ),
    ]
