# Generated by Django 5.1.6 on 2025-05-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0067_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[("schedule_reader", "Schedule Reader")],
                default="schedule_reader",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
