# Generated by Django 5.1.6 on 2025-07-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0067_alter_scenario_scenario_type_simulationtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="scenario_type",
            field=models.CharField(
                choices=[
                    ("SOURCE", "Source"),
                    ("MUATION", "Mutation"),
                    ("SIMULATION", "Simulation"),
                ],
                null=True,
            ),
        ),
    ]
