# Generated by Django 5.1.6 on 2025-07-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0067_notification_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="tco_parameters",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="level",
            field=models.CharField(
                choices=[
                    ("debug", "Debug"),
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("multi_dep_trips_in_block", "Multiple Depot Trips In Block Warning"),
                    ("unstable_sim_w_shifting_socs", "Unstable Depot Warning"),
                    ("delayed_trip", "Delayed Trip Warning"),
                    ("unexpected_error", "Unexpected Error"),
                ],
                max_length=40,
            ),
        ),
    ]
