# Generated by Django 5.1.6 on 2025-08-04 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0068_alter_scenario_scenario_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="simulationrange",
            old_name="temperature",
            new_name="temperature_average",
        ),
        migrations.AddField(
            model_name="simulationrange",
            name="temperature_extreme",
            field=models.FloatField(
                blank=True,
                default=-10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-20),
                    django.core.validators.MaxValueValidator(40),
                ],
            ),
        ),
    ]
