# Generated by Django 5.1.6 on 2025-06-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0067_notification_squashed_0068_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(choices=[("schedule_reader", "Schedule Reader")], max_length=20),
        ),
    ]
