# Generated by Django 5.1.6 on 2025-07-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0068_scenario_tco_parameters_alter_notification_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicletype",
            name="tco_parameters",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
