# Generated by Django 5.1.6 on 2025-08-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0069_rename_temperature_simulationrange_temperature_average_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicletype",
            name="max_consumption",
            field=models.FloatField(default=None, null=True),
        ),
    ]
