# Generated by Django 5.1.6 on 2025-06-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0069_alter_notification_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[("multi_dep_trips_in_block", "Multiple Depot Trips In Block")],
                max_length=40,
            ),
        ),
    ]
