# Generated by Django 5.1.6 on 2025-07-31 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0069_vehicletype_tco_parameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="batterytype",
            name="tco_parameters",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.CreateModel(
            name="ChargingPointType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("name_short", models.TextField(default=models.TextField(), null=True)),
                ("tco_parameters", models.JSONField(default=dict, null=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="area",
            name="charging_point_type_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebustoolbox.chargingpointtype",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="charging_point_type_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebustoolbox.chargingpointtype",
            ),
        ),
    ]
