# Generated by Django 5.1.6 on 2025-09-01 11:48

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


def set_random_task_ids(apps, schema_editor):
    """
    Assign a fresh UUID to every Scenario where task_id is NULL.
    This runs during the upgrade of the migration.
    """
    Scenario = apps.get_model("ebustoolbox", "Scenario")
    qs = Scenario.objects.filter(task_id__isnull=True)

    # Generate a UUID for each instance and perform a bulk update
    for scenario in qs:
        scenario.task_id = uuid.uuid4()

    Scenario.objects.bulk_update(qs, ["task_id"])


def reverse_set_random_task_ids(apps, schema_editor):
    """
    No reverse action is required – the migration is data‑destructive.
    """
    pass


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# ebustoolbox.migrations.0071_notifications_and_eflips_upgrades


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0070_vehicletype_max_consumption"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("sender", models.CharField(max_length=255)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("error", "Error"),
                            ("warning", "Warning"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(max_length=1000)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[("multi_dep_trips_in_block", "Multiple Depot Trips In Block")],
                        max_length=40,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChargingPointType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("name_short", models.TextField(default=models.TextField(), null=True)),
                ("tco_parameters", models.JSONField(default=dict, null=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="area",
            name="charging_point_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebustoolbox.chargingpointtype",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="charging_point_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebustoolbox.chargingpointtype",
            ),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="tco_parameters",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="tco_parameters",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name="batterytype",
            name="tco_parameters",
            field=models.JSONField(
                db_default={"cost_escalation": 0.01, "procurement_cost": None, "useful_life": 7},
                default=dict,
                null=True,
            ),
        ),
        # **Data‑migration to fill NULL task_id values**
        migrations.RunPython(set_random_task_ids, reverse_set_random_task_ids),
        migrations.AlterField(
            model_name="scenario",
            name="task_id",
            field=models.UUIDField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="tco_parameters",
            field=models.JSONField(
                db_default={"cost_escalation": 0.02, "procurement_cost": None, "useful_life": 20},
                default=dict,
                null=True,
            ),
        ),
        migrations.AlterModelTable(
            name="chargingpointtype",
            table="ChargingPointType",
        ),
        migrations.AlterField(
            model_name="chargingpointtype",
            name="tco_parameters",
            field=models.JSONField(
                db_default={"cost_escalation": 0.02, "procurement_cost": None, "useful_life": 20},
                default=dict,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="level",
            field=models.CharField(
                choices=[
                    ("debug", "Debug"),
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("multi_dep_trips_in_block", "Multiple Depot Trips In Block Warning"),
                    ("unstable_sim_w_shifting_socs", "Unstable Depot Warning"),
                    ("delayed_trip", "Delayed Trip Warning"),
                    ("unexpected_error", "Unexpected Error"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="scenario_type",
            field=models.CharField(
                choices=[
                    ("SOURCE", "Source"),
                    ("MUTATION", "Mutation"),
                    ("SIMULATION", "Simulation"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scenario",
            name="tco_parameters",
            field=models.JSONField(
                db_default={
                    "energy_cost": 0.18,
                    "fuel_cost": 1.5,
                    "inflation_rate": 0.02,
                    "insurance": 0.0,
                    "interest_rate": 0.04,
                    "maint_cost": 0.07,
                    "maint_cost_diesel": 0.14,
                    "maint_infr_cost": 1000.0,
                    "pef_energy": 0.038,
                    "pef_general": 0.02,
                    "pef_insurance": 0.02,
                    "pef_wages": 0.025,
                    "project_duration": 20,
                    "staff_cost": 30.0,
                    "taxes": 0.0,
                },
                default=dict,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="simulationrange",
            name="temperature_average",
            field=models.FloatField(
                blank=True,
                default=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-20),
                    django.core.validators.MaxValueValidator(40),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="simulationrange",
            name="temperature_extreme",
            field=models.FloatField(
                blank=True,
                default=-5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-20),
                    django.core.validators.MaxValueValidator(40),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="tco_parameters",
            field=models.JSONField(
                db_default={
                    "cost_escalation": 0.02,
                    "procurement_cost": None,
                    "procurement_cost_diesel": None,
                    "useful_life": 14,
                },
                default=dict,
                null=True,
            ),
        ),
    ]
