# Generated by Django 5.1.6 on 2025-07-31 08:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0070_batterytype_tco_parameters_chargingpointtype_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="area",
            old_name="charging_point_type_id",
            new_name="charging_point_type",
        ),
        migrations.RenameField(
            model_name="station",
            old_name="charging_point_type_id",
            new_name="charging_point_type",
        ),
    ]
