# Generated by Django 5.1.6 on 2025-08-21 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0070_vehicletype_max_consumption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="is_electrifiable",
            field=models.BooleanField(default=False),
        ),
    ]
