# Generated by Django 5.1.6 on 2025-09-11 12:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0070_vehicletype_max_consumption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="scenario_type",
            field=models.CharField(
                choices=[
                    ("SOURCE", "Source"),
                    ("MUTATION", "Mutation"),
                    ("SIMULATION", "Simulation"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="simulationrange",
            name="temperature_average",
            field=models.FloatField(
                blank=True,
                default=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-20),
                    django.core.validators.MaxValueValidator(40),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="simulationrange",
            name="temperature_extreme",
            field=models.FloatField(
                blank=True,
                default=-5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-20),
                    django.core.validators.MaxValueValidator(40),
                ],
            ),
        ),
        migrations.CreateModel(
            name="DepotConfigurationWish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("auto_generate", models.BooleanField(default=True)),
                ("power", models.FloatField(blank=True, null=True)),
                ("cleaning_slots", models.IntegerField(blank=True, null=True)),
                ("cleaning_duration", models.IntegerField(blank=True, null=True)),
                ("shunting_slots", models.IntegerField(blank=True, null=True)),
                ("shunting_duration", models.IntegerField(blank=True, null=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ebustoolbox.scenario",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ebustoolbox.station",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AreaInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("DIRECT_ONESIDE", "Direct Oneside"),
                            ("DIRECT_TWOSIDE", "Direct Twoside"),
                            ("LINE", "Linear"),
                        ],
                        default=None,
                        max_length=14,
                        null=True,
                    ),
                ),
                ("capacity", models.IntegerField(null=True)),
                ("power", models.FloatField(null=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ebustoolbox.scenario",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ebustoolbox.vehicletype",
                    ),
                ),
                (
                    "depot_configuration_wish",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ebustoolbox.depotconfigurationwish",
                    ),
                ),
            ],
        ),
    ]
