# Generated by Django 5.1.6 on 2025-09-16 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0071_notifications_and_eflips_upgrades_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("multi_dep_trips_in_block", "Multiple Depot Trips In Block Warning"),
                    (
                        "transformed_depot_stop_to_opp_station",
                        "Intermediate Depot Stops Transformed",
                    ),
                    ("unstable_sim_w_shifting_socs", "Unstable Depot Warning"),
                    ("delayed_trip", "Delayed Trip Warning"),
                    ("unexpected_error", "Unexpected Error"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="DepotConfigurationWish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("auto_generate", models.BooleanField(default=True)),
                ("power", models.FloatField(blank=True, null=True)),
                ("cleaning_slots", models.IntegerField(blank=True, null=True)),
                ("cleaning_duration", models.IntegerField(blank=True, null=True)),
                ("shunting_slots", models.IntegerField(blank=True, null=True)),
                ("shunting_duration", models.IntegerField(blank=True, null=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ebustoolbox.scenario",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ebustoolbox.station",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AreaInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("DIRECT_ONESIDE", "Direct Oneside"),
                            ("DIRECT_TWOSIDE", "Direct Twoside"),
                            ("LINE", "Linear"),
                        ],
                        default=None,
                        max_length=14,
                        null=True,
                    ),
                ),
                ("capacity", models.IntegerField(null=True)),
                ("power", models.FloatField(null=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ebustoolbox.scenario",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ebustoolbox.vehicletype",
                    ),
                ),
                (
                    "depot_configuration_wish",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ebustoolbox.depotconfigurationwish",
                    ),
                ),
            ],
        ),
    ]
