# Generated by Django 5.1.6 on 2025-07-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0071_rename_charging_point_type_id_area_charging_point_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="tco_parameters",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
