# Generated by Django 5.1.6 on 2025-10-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0072_alter_notification_notification_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("DRIVING", "Driving"),
                    ("CHARGING_OPPORTUNITY", "Charging Opportunity"),
                    ("CHARGING_DEPOT", "Charging Depot"),
                    ("SERVICE", "Service"),
                    ("STANDBY_DEPARTURE", "Standby Departure"),
                    ("PRECONDITIONING", "Preconditioning"),
                    ("STANDBY", "Standby"),
                ],
                default=None,
                max_length=20,
            ),
        ),
    ]
