# Generated by Django 5.1.6 on 2025-08-18 15:48

from django.db import migrations, models
import uuid

def set_random_task_ids(apps, schema_editor):
    """
    Assign a fresh UUID to every Scenario where task_id is NULL.
    This runs during the upgrade of the migration.
    """
    Scenario = apps.get_model('ebustoolbox', 'Scenario')
    qs = Scenario.objects.filter(task_id__isnull=True)

    # Generate a UUID for each instance and perform a bulk update
    for scenario in qs:
        scenario.task_id = uuid.uuid4()

    Scenario.objects.bulk_update(qs, ['task_id'])


def reverse_set_random_task_ids(apps, schema_editor):
    """
    No reverse action is required – the migration is data‑destructive.
    """
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0072_station_tco_parameters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batterytype",
            name="tco_parameters",
            field=models.JSONField(
                db_default={"cost_escalation": 0.01, "procurement_cost": None, "useful_life": 7},
                default=dict,
                null=True,
            ),
        ),
        # **Data‑migration to fill NULL task_id values**
        migrations.RunPython(set_random_task_ids, reverse_set_random_task_ids),
        migrations.AlterField(
            model_name="scenario",
            name="task_id",
            field=models.UUIDField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="tco_parameters",
            field=models.JSONField(
                db_default={
                    "energy_cost": 0.18,
                    "fuel_cost": 1.5,
                    "inflation_rate": 0.02,
                    "insurance": 0.0,
                    "interest_rate": 0.04,
                    "maint_cost": 0.07,
                    "maint_cost_diesel": 0.14,
                    "maint_infr_cost": 1000.0,
                    "pef_energy": 0.038,
                    "pef_general": 0.02,
                    "pef_insurance": 0.02,
                    "pef_wages": 0.025,
                    "project_duration": 20,
                    "staff_cost": 30.0,
                    "taxes": 0.0,
                },
                default=dict,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="tco_parameters",
            field=models.JSONField(
                db_default={"cost_escalation": 0.02, "procurement_cost": None, "useful_life": 20},
                default=dict,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="tco_parameters",
            field=models.JSONField(
                db_default={
                    "cost_escalation": 0.02,
                    "procurement_cost": None,
                    "procurement_cost_diesel": None,
                    "useful_life": 14,
                },
                default=dict,
                null=True,
            ),
        ),
    ]
