# Generated by Django 5.1.6 on 2025-08-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0073_alter_batterytype_tco_parameters_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="chargingpointtype",
            table="ChargingPointType",
        ),
    ]
