# Generated by Django 5.1.6 on 2025-08-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0073_alter_event_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="is_electrifiable",
            field=models.BooleanField(default=False),
        ),
    ]
