# Generated by Django 5.1.6 on 2025-10-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0074_alter_station_is_electrifiable_default"),
    ]

    operations = [
        migrations.RenameField(
            model_name="depotconfigurationwish",
            old_name="power",
            new_name="default_power",
        ),
        migrations.AddField(
            model_name="areainformation",
            name="block_length",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="depotconfigurationwish",
            name="standard_block_length",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
