# Generated by Django 5.1.6 on 2025-08-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0074_alter_chargingpointtype_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargingpointtype",
            name="tco_parameters",
            field=models.JSONField(
                db_default={"cost_escalation": 0.02, "procurement_cost": None, "useful_life": 20},
                default=dict,
                null=True,
            ),
        ),
    ]
