# Generated by Django 5.1.6 on 2025-08-18 16:02

import django.contrib.gis.db.models.fields
from django.db import migrations


def convert_geometries_to_2d(apps, schema_editor):
    """Convert 3D geometries to 2D by removing Z dimension"""
    if schema_editor.connection.vendor == 'postgresql':
        # For PostGIS databases
        with schema_editor.connection.cursor() as cursor:
            # Convert AssocrouteStation location from 3D to 2D
            cursor.execute("""
                           UPDATE "AssocRouteStation"
                           SET location_temp = ST_Force2D(location)
                           WHERE location IS NOT NULL
                             AND ST_CoordDim(location) = 3
                           """)
            cursor.execute("""
                           UPDATE "AssocRouteStation"
                           SET location_temp = location
                           WHERE location IS NOT NULL
                             AND ST_CoordDim(location) = 2
                           """)

            # Convert Route geom from 3D to 2D
            cursor.execute("""
                           UPDATE "Route"
                           SET geom_temp = ST_Force2D(geom)
                           WHERE geom IS NOT NULL
                             AND ST_CoordDim(geom) = 3
                           """)
            cursor.execute("""
                           UPDATE "Route"
                           SET geom_temp = geom
                           WHERE geom IS NOT NULL
                             AND ST_CoordDim(geom) = 2
                           """)

            # Convert Station geom from 3D to 2D
            cursor.execute("""
                           UPDATE "Station"
                           SET geom_temp = ST_Force2D(geom)
                           WHERE geom IS NOT NULL
                             AND ST_CoordDim(geom) = 3
                           """)
            cursor.execute("""
                           UPDATE "Station"
                           SET geom_temp = geom
                           WHERE geom IS NOT NULL
                             AND ST_CoordDim(geom) = 2
                           """)
    else:
        raise NotImplementedError("This migration only supports PostgreSQL with PostGIS.")


def convert_geometries_to_3d(apps, schema_editor):
    """Convert 2D geometries to 3D by adding Z=0"""
    if schema_editor.connection.vendor == 'postgresql':
        # For PostGIS databases
        with schema_editor.connection.cursor() as cursor:
            # Convert AssocrouteStation location from 2D to 3D
            cursor.execute("""
                           UPDATE "AssocRouteStation"
                           SET location_temp = ST_Force3D(location)
                           WHERE location IS NOT NULL
                             AND ST_CoordDim(location) = 2
                           """)
            cursor.execute("""
                           UPDATE "AssocRouteStation"
                           SET location_temp = location
                           WHERE location IS NOT NULL
                             AND ST_CoordDim(location) = 3
                           """)

            # Convert Route geom from 2D to 3D
            cursor.execute("""
                           UPDATE "Route"
                           SET geom_temp = ST_Force3D(geom)
                           WHERE geom IS NOT NULL
                             AND ST_CoordDim(geom) = 2
                           """)
            cursor.execute("""
                           UPDATE "Route"
                           SET geom_temp = geom
                           WHERE geom IS NOT NULL
                             AND ST_CoordDim(geom) = 3
                           """)

            # Convert Station geom from 2D to 3D
            cursor.execute("""
                           UPDATE "Station"
                           SET geom_temp = ST_Force3D(geom)
                           WHERE geom IS NOT NULL
                             AND ST_CoordDim(geom) = 2
                           """)
            cursor.execute("""
                           UPDATE "Station"
                           SET geom_temp = geom
                           WHERE geom IS NOT NULL
                             AND ST_CoordDim(geom) = 3
                           """)
    else:
        raise NotImplementedError("This migration only supports PostgreSQL with PostGIS.")


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0075_alter_chargingpointtype_tco_parameters"),
    ]

    operations = [
        # Step 1: Add temporary columns with new geometry type (2D)
        migrations.AddField(
            model_name="assocroutestation",
            name="location_temp",
            field=django.contrib.gis.db.models.fields.PointField(
                null=True, srid=4326, dim=2
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="geom_temp",
            field=django.contrib.gis.db.models.fields.LineStringField(
                null=True, srid=4326, dim=2
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="geom_temp",
            field=django.contrib.gis.db.models.fields.PointField(
                null=True, srid=4326, dim=2
            ),
        ),

        # Step 2: Copy and convert data from original columns to temporary columns
        migrations.RunPython(
            convert_geometries_to_2d,
            convert_geometries_to_3d,  # Reverse operation
        ),

        # Step 3: Remove original columns
        migrations.RemoveField(
            model_name="assocroutestation",
            name="location",
        ),
        migrations.RemoveField(
            model_name="route",
            name="geom",
        ),
        migrations.RemoveField(
            model_name="station",
            name="geom",
        ),

        # Step 4: Rename temporary columns to original names
        migrations.RenameField(
            model_name="assocroutestation",
            old_name="location_temp",
            new_name="location",
        ),
        migrations.RenameField(
            model_name="route",
            old_name="geom_temp",
            new_name="geom",
        ),
        migrations.RenameField(
            model_name="station",
            old_name="geom_temp",
            new_name="geom",
        ),
    ]