# Generated by Django 5.1.6 on 2025-10-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0075_rename_power_depotconfigurationwish_default_power_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("multi_dep_trips_in_block", "Multiple Depot Trips In Block Warning"),
                    (
                        "transformed_depot_stop_to_opp_station",
                        "Intermediate Depot Stops Transformed",
                    ),
                    ("unstable_sim_w_shifting_socs", "Unstable Depot Warning"),
                    ("delayed_trip", "Delayed Trip Warning"),
                    ("unexpected_error", "Unexpected Error"),
                    ("added_electrification", "Added Electrification"),
                    ("low_soc_blocks", "Low Soc Blocks"),
                ],
                max_length=40,
            ),
        ),
    ]
