# Generated by Django 5.1.6 on 2025-10-30 19:34

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


def add_default_length_width_height(apps, schema_editor):
    VehicleType = apps.get_model("ebustoolbox", "VehicleType")
    VehicleType.objects.filter(width__isnull=True).update(width=2.55)
    VehicleType.objects.filter(height__isnull=True).update(height=3.1)
    VehicleType.objects.filter(length__isnull=True).update(length=12)


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0076_alter_notification_notification_type"),
    ]

    operations = [
        migrations.RunPython(add_default_length_width_height),
        migrations.AlterField(
            model_name="vehicletype",
            name="battery_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebustoolbox.batterytype",
            ),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="consumption",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="height",
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="length",
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="max_consumption",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="name_short",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="tco_parameters",
            field=models.JSONField(
                blank=True,
                db_default={
                    "cost_escalation": 0.02,
                    "procurement_cost": None,
                    "procurement_cost_diesel": None,
                    "useful_life": 14,
                },
                default=dict,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="v2g_curve",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.FloatField(), size=2
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="width",
            field=models.FloatField(default=None),
        ),
    ]
