# Generated by Django 5.1.6 on 2025-11-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0077_alter_vehicletype_battery_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("multi_dep_trips_in_block", "Multiple Depot Trips In Block Warning"),
                    ("merged_station_trips_and_routes", "Merged Stations For Inconsistent Trips"),
                    (
                        "transformed_depot_stop_to_opp_station",
                        "Intermediate Depot Stops Transformed",
                    ),
                    ("station_optimization_skipped", "Station Optimization Skipped"),
                    ("unstable_sim_w_shifting_socs", "Unstable Depot Warning"),
                    ("delayed_trip", "Delayed Trip Warning"),
                    ("unexpected_error", "Unexpected Error"),
                    ("added_electrification", "Added Electrification"),
                    ("low_soc_blocks", "Low Soc Blocks"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="eflips_depot_options",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="scenario_type",
            field=models.CharField(
                choices=[
                    ("SOURCE", "Source"),
                    ("MUTATION", "Mutation"),
                    ("SIMULATION", "Simulation"),
                    ("PUBLIC_DATA", "Public Data"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="simba_options",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="tco_parameters",
            field=models.JSONField(
                blank=True,
                db_default={
                    "energy_cost": 0.18,
                    "fuel_cost": 1.5,
                    "inflation_rate": 0.02,
                    "insurance": 0.0,
                    "interest_rate": 0.04,
                    "maint_cost": 0.07,
                    "maint_cost_diesel": 0.14,
                    "maint_infr_cost": 1000.0,
                    "pef_energy": 0.038,
                    "pef_general": 0.02,
                    "pef_insurance": 0.02,
                    "pef_wages": 0.025,
                    "project_duration": 20,
                    "staff_cost": 30.0,
                    "taxes": 0.0,
                },
                default=dict,
                null=True,
            ),
        ),
    ]
