# Generated by Django 5.1.6 on 2025-11-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0077_alter_vehicletype_battery_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="area_type",
            field=models.CharField(
                choices=[
                    ("DIRECT_ONESIDE", "Direkt einseitig"),
                    ("DIRECT_TWOSIDE", "Direkt Zweiseitig"),
                    ("LINE", "Linie"),
                ],
                default=None,
                max_length=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="areainformation",
            name="area_type",
            field=models.CharField(
                choices=[
                    ("DIRECT_ONESIDE", "Direkt einseitig"),
                    ("DIRECT_TWOSIDE", "Direkt Zweiseitig"),
                    ("LINE", "Linie"),
                ],
                default=None,
                max_length=14,
                null=True,
            ),
        ),
    ]
