# Generated by Django 5.1.6 on 2025-11-11 16:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0077_alter_vehicletype_battery_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scenariowizardoptions",
            name="scenario",
        ),
        migrations.AlterField(
            model_name="area",
            name="area_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIRECT_ONESIDE", "Direct Oneside"),
                    ("DIRECT_TWOSIDE", "Direct Twoside"),
                    ("LINE", "Linear"),
                ],
                default=None,
                max_length=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="bounding_box",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, default=None, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="charging_point_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebustoolbox.chargingpointtype",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="area",
            name="name_short",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="area",
            name="row_count",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="area",
            name="vehicle_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebustoolbox.vehicletype",
            ),
        ),
        migrations.AlterField(
            model_name="areainformation",
            name="area_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIRECT_ONESIDE", "Direct Oneside"),
                    ("DIRECT_TWOSIDE", "Direct Twoside"),
                    ("LINE", "Linear"),
                ],
                default=None,
                max_length=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="areainformation",
            name="capacity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="areainformation",
            name="power",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assocroutestation",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, dim=3, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="batterytype",
            name="tco_parameters",
            field=models.JSONField(
                blank=True,
                db_default={"cost_escalation": 0.01, "procurement_cost": None, "useful_life": 7},
                default=dict,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="depot",
            name="bounding_box",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, default=None, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="depotmutation",
            name="mutated_original_depot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mutateddepot",
                to="ebustoolbox.depot",
            ),
        ),
        migrations.AlterField(
            model_name="depotmutation",
            name="original_depot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="originaldepot",
                to="ebustoolbox.depot",
            ),
        ),
        migrations.AlterField(
            model_name="depotmutation",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebustoolbox.scenario",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebustoolbox.area",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebustoolbox.station",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="timeseries",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebustoolbox.trip",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebustoolbox.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("multi_dep_trips_in_block", "Multiple Depot Trips In Block Warning"),
                    ("merged_station_trips_and_routes", "Merged Stations For Inconsistent Trips"),
                    (
                        "transformed_depot_stop_to_opp_station",
                        "Intermediate Depot Stops Transformed",
                    ),
                    ("station_optimization_skipped", "Station Optimization Skipped"),
                    ("unstable_sim_w_shifting_socs", "Unstable Depot Warning"),
                    ("delayed_trip", "Delayed Trip Warning"),
                    ("unexpected_error", "Unexpected Error"),
                    ("added_electrification", "Added Electrification"),
                    ("low_soc_blocks", "Low Soc Blocks"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="process",
            name="availability",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="process",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="process",
            name="electric_power",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="process",
            name="name_short",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rotation",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rotation",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="ebustoolbox.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="geom",
            field=django.contrib.gis.db.models.fields.LineStringField(
                blank=True, dim=3, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebustoolbox.line",
            ),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="eflips_depot_options",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="scenario_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SOURCE", "Source"),
                    ("MUTATION", "Mutation"),
                    ("SIMULATION", "Simulation"),
                    ("PUBLIC_DATA", "Public Data"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="simba_options",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="tco_parameters",
            field=models.JSONField(
                blank=True,
                db_default={
                    "energy_cost": 0.18,
                    "fuel_cost": 1.5,
                    "inflation_rate": 0.02,
                    "insurance": 0.0,
                    "interest_rate": 0.04,
                    "maint_cost": 0.07,
                    "maint_cost_diesel": 0.14,
                    "maint_infr_cost": 1000.0,
                    "pef_energy": 0.038,
                    "pef_general": 0.02,
                    "pef_insurance": 0.02,
                    "pef_wages": 0.025,
                    "project_duration": 20,
                    "staff_cost": 30.0,
                    "taxes": 0.0,
                },
                default=dict,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="simulationrange",
            name="end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="simulationrange",
            name="start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="amount_charging_places",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="charge_type",
            field=models.CharField(
                blank=True,
                choices=[("depb", "Depot"), ("oppb", "Opportunity")],
                default=None,
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="charging_point_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebustoolbox.chargingpointtype",
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, dim=3, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="power_per_charger",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="power_total",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="tco_parameters",
            field=models.JSONField(
                blank=True,
                db_default={"cost_escalation": 0.02, "procurement_cost": None, "useful_life": 20},
                default=dict,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="voltage_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HV", "Voltage Hv"),
                    ("HV_MV", "Voltage Hv Mv"),
                    ("MV", "Voltage Mv"),
                    ("MV_LV", "Voltage Mv Lv"),
                    ("LV", "Voltage Lv"),
                ],
                default=None,
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stationmutation",
            name="mutated_original_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mutatedstation",
                to="ebustoolbox.station",
            ),
        ),
        migrations.AlterField(
            model_name="stationmutation",
            name="original_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="originalstation",
                to="ebustoolbox.station",
            ),
        ),
        migrations.AlterField(
            model_name="stationmutation",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebustoolbox.scenario",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="loaded_mass",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="vehicletypemutation",
            name="mutated_vehicle_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mutatedvehicletype",
                to="ebustoolbox.vehicletype",
            ),
        ),
        migrations.AlterField(
            model_name="vehicletypemutation",
            name="original_vehicle_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="originalvehicletype",
                to="ebustoolbox.vehicletype",
            ),
        ),
        migrations.AlterField(
            model_name="vehicletypemutation",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebustoolbox.scenario",
            ),
        ),
        migrations.AlterField(
            model_name="vehicletypeselection",
            name="default_vehicle_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formdefaultvehicletype",
                to="ebustoolbox.vehicletype",
            ),
        ),
        migrations.DeleteModel(
            name="ElectrificationOptions",
        ),
        migrations.DeleteModel(
            name="ScenarioWizardOptions",
        ),
    ]
