# Generated by Django 5.1.6 on 2025-11-12 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0078_remove_scenariowizardoptions_scenario_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DepotMutation",
        ),
    ]
