# Generated by Django 5.1.6 on 2025-11-25 08:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0080_remove_electrificationoptions_electrified_stations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="scenario_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SOURCE", "Source"),
                    ("SOURCE_FILE", "Source File"),
                    ("MUTATION", "Mutation"),
                    ("SIMULATION", "Simulation"),
                    ("PUBLIC_DATA", "Public Data"),
                ],
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SimulationTemperatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "temperature_average",
                    models.FloatField(
                        blank=True,
                        default=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-20),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "temperature_extreme",
                    models.FloatField(
                        blank=True,
                        default=-5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-20),
                            django.core.validators.MaxValueValidator(40),
                        ],
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ebustoolbox.scenario"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="SimulationRange",
        ),
    ]
