# Generated by Django 5.1.6 on 2025-11-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0080_remove_electrificationoptions_electrified_stations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="area_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIRECT_ONESIDE", "Schrägabstellung"),
                    ("DIRECT_TWOSIDE", "Schrägabstellung in Doppelreihe"),
                    ("LINE", "Blockabstellung"),
                ],
                default=None,
                max_length=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="areainformation",
            name="area_type",
            field=models.CharField(
                choices=[
                    ("DIRECT_ONESIDE", "Schrägabstellung"),
                    ("DIRECT_TWOSIDE", "Schrägabstellung in Doppelreihe"),
                    ("LINE", "Blockabstellung"),
                ],
                default=None,
                max_length=14,
                null=True,
            ),
        ),
    ]
