# Generated by Django 5.1.6 on 2026-01-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0082_alter_scenario_scenario_type_simulationtemperatures_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batterytype",
            name="tco_parameters",
            field=models.JSONField(
                blank=True,
                db_default={"cost_escalation": 0.01, "procurement_cost": None, "useful_life": 7},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chargingpointtype",
            name="tco_parameters",
            field=models.JSONField(
                db_default={"cost_escalation": 0.02, "procurement_cost": None, "useful_life": 20},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="tco_parameters",
            field=models.JSONField(
                blank=True,
                db_default={
                    "energy_cost": 0.18,
                    "fuel_cost": 1.5,
                    "inflation_rate": 0.02,
                    "insurance": 0.0,
                    "interest_rate": 0.04,
                    "maint_cost": 0.07,
                    "maint_cost_diesel": 0.14,
                    "maint_infr_cost": 1000.0,
                    "pef_energy": 0.038,
                    "pef_general": 0.02,
                    "pef_insurance": 0.02,
                    "pef_wages": 0.025,
                    "project_duration": 20,
                    "staff_cost": 30.0,
                    "taxes": 0.0,
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="tco_parameters",
            field=models.JSONField(
                blank=True,
                db_default={"cost_escalation": 0.02, "procurement_cost": None, "useful_life": 20},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="tco_parameters",
            field=models.JSONField(
                blank=True,
                db_default={
                    "cost_escalation": 0.02,
                    "procurement_cost": None,
                    "procurement_cost_diesel": None,
                    "useful_life": 14,
                },
                null=True,
            ),
        ),
    ]
