# Generated by Django 5.1.6 on 2026-02-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0083_alter_batterytype_tco_parameters_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="tco_parameters",
            field=models.JSONField(
                blank=True,
                db_default={
                    "energy_cost": 0.18,
                    "fuel_cost": 1.5,
                    "inflation_rate": 0.02,
                    "insurance": 0.0,
                    "interest_rate": 0.04,
                    "maint_cost": 0.07,
                    "maint_cost_diesel": 0.14,
                    "maint_infr_cost": 1000.0,
                    "pef_energy": 0.02,
                    "pef_fuel": 0.02,
                    "pef_general": 0.02,
                    "pef_insurance": 0.02,
                    "pef_wages": 0.02,
                    "project_duration": 20,
                    "staff_cost": 30.0,
                    "taxes": 0.0,
                },
                null=True,
            ),
        ),
    ]
