# Generated by Django 5.1.6 on 2026-02-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0084_alter_scenario_tco_parameters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batterytype",
            name="tco_parameters",
            field=models.JSONField(
                blank=True,
                db_default={"cost_escalation": 0.01, "procurement_cost": 0, "useful_life": 7},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chargingpointtype",
            name="tco_parameters",
            field=models.JSONField(
                db_default={"cost_escalation": 0.02, "procurement_cost": 0, "useful_life": 20},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="tco_parameters",
            field=models.JSONField(
                blank=True,
                db_default={"cost_escalation": 0.02, "procurement_cost": 0, "useful_life": 20},
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehicletype",
            name="tco_parameters",
            field=models.JSONField(
                blank=True,
                db_default={
                    "cost_escalation": 0.02,
                    "procurement_cost": 550000,
                    "procurement_cost_diesel": 250000,
                    "useful_life": 14,
                },
                null=True,
            ),
        ),
    ]
