# Generated by Django 5.1.6 on 2025-11-20 08:35

from uuid import uuid4
from django.db import migrations
from django.db.models import Prefetch


def set_scenario_progress(apps, schema_editor):
    RUN_SIM = "RUNNING_SIMULATION"
    Scenario = apps.get_model("ebustoolbox", "Scenario")
    Progress = apps.get_model("core", "Progress")

    # Find all mutations, which have a progress
    mutation_scenarios_w_progress = Scenario.objects.filter(
        scenario_type="MUTATION", progress__progress_type=RUN_SIM
    ).prefetch_related(
        Prefetch("progress_set", queryset=Progress.objects.filter(progress_type=RUN_SIM))
    )
    print(f"found {mutation_scenarios_w_progress}")

    new_progresses = []
    for mutation in mutation_scenarios_w_progress:
        children = Scenario.objects.filter(parent=mutation).prefetch_related("progress_set")
        print(f"found children {children}")
        progress = mutation.progress_set.first()
        for child in children:
            if child.progress_set.filter(progress_type=RUN_SIM).exists():
                continue
            p = Progress(
                task_id=uuid4(),
                scenario=child,
                progress_type=RUN_SIM,
                success=progress.success,
                running=progress.running,
                errors=progress.errors,
            )
            new_progresses.append(p)
    print(Progress.objects.bulk_create(new_progresses))


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0086_scenario_tco_result"),
    ]

    operations = [
        migrations.RunPython(set_scenario_progress, lambda app, schema_editor: ()),
    ]
