# Generated by Django 5.1.6 on 2026-04-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0087_set_missing_scenario_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicletype",
            name="energy_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("battery_electric", "Battery Electric"),
                    ("diesel", "Diesel"),
                    ("hydrogen", "Hydrogen"),
                ],
                default="battery_electric",
                null=True,
            ),
        ),
    ]
