# Generated by Django 5.1.6 on 2026-04-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0087_set_missing_scenario_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='energy_source',
            field=models.CharField(choices=[('BATTERY_ELECTRIC', 'Battery Electric'), ('DIESEL', 'Diesel'), ('HYDROGEN', 'Hydrogen')], db_default='BATTERY_ELECTRIC', default='BATTERY_ELECTRIC', max_length=16),
        ),
    ]
