# Generated by Django 5.1.6 on 2026-04-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0088_vehicletype_energy_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicletype",
            name="energy_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BATTERY_ELECTRIC", "Battery Electric"),
                    ("DIESEL", "Diesel"),
                    ("HYDROGEN", "Hydrogen"),
                ],
                default="BATTERY_ELECTRIC",
                null=True,
            ),
        ),
    ]
