# Generated by Django 5.1.6 on 2026-04-29 12:21

from django.db import migrations


def fix_energy_sources(apps, schema_editor):
    VehicleType = apps.get_model("ebustoolbox", "VehicleType")
    VehicleType.objects.filter(energy_source="battery_electric").update(
        energy_source="BATTERY_ELECTRIC"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0089_alter_vehicletype_energy_source"),
    ]

    operations = [
        migrations.RunPython(fix_energy_sources, lambda app, schema_editor: ()),
    ]
