# Generated by Django 5.1.6 on 2026-05-14 16:02

from django.db import migrations, models
from ebustoolbox.tasks import migrate_legacy_tco_forward


def migrate_tco_parameters_forward(apps, schema_editor):
    """Convert each Scenario's tco_parameters from the legacy flat schema to the
    nested schema required by eflips-tco's revenue-km TCO calculator.

    Legacy keys → new keys:
      energy_cost, fuel_cost (scalar)        → fuel_cost {electricity, diesel}
      maint_cost, maint_cost_diesel          → vehicle_maint_cost {electricity, diesel}
      maint_infr_cost                        → infra_maint_cost
      pef_general, pef_wages, pef_energy,
      pef_fuel, pef_insurance                → cost_escalation_rate
                                               {general, staff, electricity, diesel, insurance}

    Unknown extra keys are preserved. Already-migrated rows (no legacy keys present
    and nested keys already populated) are left untouched.
    """
    Scenario = apps.get_model("ebustoolbox", "Scenario")
    for scenario in Scenario.objects.all():
        params = scenario.tco_parameters or {}
        new_params = migrate_legacy_tco_forward(params)
        if new_params is None:
            continue
        scenario.tco_parameters = new_params
        scenario.save(update_fields=["tco_parameters"])


def migrate_tco_parameters_backward(apps, schema_editor):
    """Convert nested schema back to the legacy flat schema."""
    Scenario = apps.get_model("ebustoolbox", "Scenario")
    for scenario in Scenario.objects.all():
        params = scenario.tco_parameters or {}
        if "cost_escalation_rate" not in params and "fuel_cost" not in params:
            continue
        new_params = dict(params)
        fuel = params.get("fuel_cost") or {}
        if isinstance(fuel, dict):
            new_params["energy_cost"] = fuel.get("electricity", 0.18)
            new_params["fuel_cost"] = fuel.get("diesel", 1.5)
        maint = params.get("vehicle_maint_cost") or {}
        if isinstance(maint, dict):
            new_params["maint_cost"] = maint.get("electricity", 0.07)
            new_params["maint_cost_diesel"] = maint.get("diesel", 0.14)
            new_params.pop("vehicle_maint_cost", None)
        new_params["maint_infr_cost"] = params.get("infra_maint_cost", 1000.0)
        new_params.pop("infra_maint_cost", None)
        esc = params.get("cost_escalation_rate") or {}
        if isinstance(esc, dict):
            new_params["pef_general"] = esc.get("general", 0.02)
            new_params["pef_wages"] = esc.get("staff", 0.02)
            new_params["pef_energy"] = esc.get("electricity", 0.02)
            new_params["pef_fuel"] = esc.get("diesel", 0.02)
            new_params["pef_insurance"] = esc.get("insurance", 0.02)
            new_params.pop("cost_escalation_rate", None)
        scenario.tco_parameters = new_params
        scenario.save(update_fields=["tco_parameters"])


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0090_auto_20260429_1221"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="tco_parameters",
            field=models.JSONField(
                blank=True,
                db_default={
                    "cost_escalation_rate": {
                        "diesel": 0.02,
                        "electricity": 0.02,
                        "general": 0.02,
                        "insurance": 0.02,
                        "staff": 0.02,
                    },
                    "fuel_cost": {"diesel": 1.5, "electricity": 0.18},
                    "inflation_rate": 0.02,
                    "infra_maint_cost": 1000.0,
                    "insurance": 0.0,
                    "interest_rate": 0.04,
                    "project_duration": 20,
                    "staff_cost": 30.0,
                    "taxes": 0.0,
                    "vehicle_maint_cost": {"diesel": 0.14, "electricity": 0.07},
                },
                null=True,
            ),
        ),
        migrations.RunPython(migrate_tco_parameters_forward, migrate_tco_parameters_backward),
    ]
