# Generated by Django 5.1.6 on 2026-06-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0090_auto_20260429_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='height',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='length',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='width',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
