# Generated by Django 5.1.6 on 2026-06-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebustoolbox', '0091_alter_scenario_tco_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('deleted_inconsistent_rotation', 'Deleted Inconsistent Rotation'), ('multi_dep_trips_in_block', 'Multiple Depot Trips In Block Warning'), ('merged_station_trips_and_routes', 'Merged Stations For Inconsistent Trips'), ('transformed_depot_stop_to_opp_station', 'Intermediate Depot Stops Transformed'), ('station_optimization_skipped', 'Station Optimization Skipped'), ('unstable_sim_w_shifting_socs', 'Unstable Depot Warning'), ('delayed_trip', 'Delayed Trip Warning'), ('unexpected_error', 'Unexpected Error'), ('added_electrification', 'Added Electrification'), ('low_soc_blocks', 'Low Soc Blocks')], max_length=40),
        ),
    ]
