# Generated by Django 5.1.6 on 2026-08-10 09:15
# Default vehicle types should always contain a battery type. this migration adds it to the default scenario
# if vehicletypes are added to the default scenario they need to contain battery types.
# this is not enforced by the db. Without a battery type the costs page does not behave like expected
#
from django.db import migrations


def add_battery_types(apps, schema_editor):
    """Add default battery types to default scenario vehicle types.
    VehicleTypes with a battery_type are unaffected
    """
    VehicleType = apps.get_model("ebustoolbox", "VehicleType")
    DefaultScenario = apps.get_model("ebustoolbox", "DefaultScenario")
    BatteryType = apps.get_model("ebustoolbox", "BatteryType")
    #
    default_scenario = DefaultScenario.objects.first().scenario
    # default vehicle types without a battery
    vts = VehicleType.objects.filter(scenario=default_scenario, battery_type__isnull=True)
    batteries = []
    for _ in vts:
        bt = BatteryType(scenario=default_scenario, specific_mass=2.5, chemistry={"type": "Li-ion"})
        batteries.append(bt)
    batteries = BatteryType.objects.bulk_create(batteries)

    for vt, bat in zip(vts, batteries, strict=True):
        vt.battery_type = bat
    VehicleType.objects.bulk_update(vts, ["battery_type"])


class Migration(migrations.Migration):
    dependencies = [
        ("ebustoolbox", "0092_alter_notification_notification_type"),
    ]

    operations = [migrations.RunPython(add_battery_types, migrations.RunPython.noop)]
