# Generated by Django 5.1.6 on 2026-08-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0093_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="tco_parameters",
            field=models.JSONField(
                blank=True,
                db_default={
                    "cost_escalation_rate": {
                        "diesel": 0.02,
                        "electricity": 0.02,
                        "general": 0.02,
                        "insurance": 0.02,
                        "staff": 0.02,
                    },
                    "eta_avail": 0.9,
                    "fuel_cost": {"diesel": 1.5, "electricity": 0.18},
                    "inflation_rate": 0.02,
                    "infra_maint_cost": 1000.0,
                    "insurance": 0.0,
                    "interest_rate": 0.04,
                    "project_duration": 20,
                    "staff_cost": 30.0,
                    "taxes": 0.0,
                    "vehicle_maint_cost": {"diesel": 0.14, "electricity": 0.07},
                },
                null=True,
            ),
        ),
    ]
