# Generated by Django 5.1.6 on 2026-08-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    """Follow eflips-model 11.2.0, which adds ``lca_parameters`` and retypes
    ``BatteryType.chemistry``.

    django-simba does not run eflips-model's alembic revisions -- there is no
    ``alembic_version`` table and Django owns these tables outright -- so the DDL is
    reproduced here. It is deliberately not a copy: upstream converts ``chemistry``
    with ``chemistry::text``, which keeps the JSON quotes, and a value that came out as
    ``"NMC622"`` rather than ``NMC622`` would fail the ``startswith("NMC")`` test that
    eflips-impact uses to pick the battery emission factors, silently costing every
    NMC battery the LFP figures. Extracting the scalar with ``#>> '{}'`` is what drops
    the quotes.
    """

    dependencies = [
        ("ebustoolbox", "0094_alter_scenario_tco_parameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="batterytype",
            name="lca_parameters",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chargingpointtype",
            name="lca_parameters",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="lca_parameters",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    # COALESCE covers a stored JSON ``null``, the one value whose
                    # extraction is SQL NULL; the column is NOT NULL. A stored object
                    # such as {} converts to its own text form rather than to NULL, so
                    # nothing is lost even where the column was used as eFLIPS-LCA
                    # originally intended.
                    sql="""
                        ALTER TABLE "BatteryType"
                        ALTER COLUMN "chemistry" TYPE text
                        USING COALESCE("chemistry" #>> '{}', '');
                    """,
                    reverse_sql="""
                        ALTER TABLE "BatteryType"
                        ALTER COLUMN "chemistry" TYPE jsonb
                        USING to_jsonb("chemistry");
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="batterytype",
                    name="chemistry",
                    field=models.TextField(blank=True, default=""),
                ),
            ],
        ),
    ]
