# Generated by Django 5.1.6 on 2026-08-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebustoolbox", "0094_alter_vehicletype_dimensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="charge_type",
            field=models.CharField(
                blank=True,
                choices=[("depb", "Depotladung"), ("oppb", "Gelegenheitsladung")],
                default=None,
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="voltage_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HV", "Hochspannung"),
                    ("HV_MV", "Hoch-/Mittelspannung"),
                    ("MV", "Mittelspannung"),
                    ("MV_LV", "Mittel-/Niederspannung"),
                    ("LV", "Niederspannung"),
                ],
                default=None,
                max_length=5,
                null=True,
            ),
        ),
    ]
