BUS_DROPDOWN = "bus-dropdown"
SELECT_ALL_BUSES_BUTTON = "select-all-buses-button"
BAR_CHART = "bar-chart"
NUMBER_REPORT = "number-report"
SCATTER_CHART = "scatter-chart"
SOC_HISTOGRAM = "soc-histogram"
