"""
Django settings for ebusdjango project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from django.utils.translation import gettext_lazy as _

import environ
from ebus_map.settings import *  # noqa

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Root dir is a parent directory
ROOT_DIR = environ.Path(__file__) - 2

# Read environment variables
env = environ.Env()

# Read .env file
# OS environment variables take precedence over variables from .env file
env.read_env(str(ROOT_DIR.path(".env")))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
SECRET_KEY = env("DJANGO_SECRET_KEY")
DJANGO_ELEVATION_TOKEN = env.str("DJANGO_ELEVATION_TOKEN", "notoken")
OPENELEVATION_URL = env.str("OPENELEVATION_URL", "")
SEARCH_STATION_LOCATIONS = env.bool("DJANGO_SEARCH_STATIONS", default=True)
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1", "*"])
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=["http://127.0.0.1"])

# Source to xyzascii zip of elevations
ELEVATION_SOURCE_URL = env.str(
    "ELEVATION_SOURCE_URL",
    "https://daten.gdz.bkg.bund.de/produkte/dgm/dgm200/aktuell/dgm200.utm32s.gridascii.zip",
)

DATA_UPLOAD_MAX_NUMBER_FIELDS = env.int(
    "DJANGO_DATA_UPLOAD_MAX_NUMBER_FIELDS", 3000
)  # higher than the count of fields. StationsView can have a couple of hundred stations with 5 fields each.
# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    # custom apps
    "core",
    "data_scrapers",
    "ebustoolbox",
    "elevation_api",
    "temperatures",
    "django_mapengine",
    "ebus_map",
    "bootstrap4",
    "tailwind",
    "tailwind_theme",
    "widget_tweaks",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # if the header and footer tags are in use this setting should be used. No problem if not in use
    "core.middleware.TimezoneMiddleware",
    # activate the language based on user cookie
    "core.middleware.LanguageMiddleware",
]

ROOT_URLCONF = "ebusdjango.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "ebus_map/static"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ebusdjango.wsgi.application"

# Email
# dummy: write to console until real server exists
# real: django.core.mail.backends.smtp.EmailBackend
# for Exchange, use core.email.NoCheckEmailBackend to work with missing/self-cert SSL
EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST", default=None)
EMAIL_PORT = env("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default=None)
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default=None)
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

LOGIN_URL = "login"  # redirect after password reset done (Django default: accounts/login)
LOGIN_REDIRECT_URL = "/"  # redirect to landing page after login
# LOGOUT_REDIRECT_URL = "/"  # don't set: show custom logged out view

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# ToDo Set up your own postgis databank and fill in the needed
#  data. Patrick wrote an HowTo for Linux users
DATABASES = {"default": env.db("DATABASE_URL")}

CELERY_TASK_ALWAYS_EAGER = env.bool("CELERY_TASK_ALWAYS_EAGER", default=True)
# if set, eager tasks will propagate exceptions
CELERY_TASK_EAGER_PROPAGATES = env.bool("CELERY_TASK_EAGER_PROPAGATES", default=True)
# if set, eager tasks will save results in backend
CELERY_TASK_STORE_EAGER_RESULT = env.bool("CELERY_TASK_STORE_EAGER_RESULT", default=True)
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default=None)
# Recommended celery backend for persistent storage is REDIS.
# rpc is an alternative which does not need extra dependency but is epheremal.
# Once fetched the results are gone.
# The status Started can only be fetched once.
# Therefore the status of tasks can not be determined accurately.
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="rpc://")
CELERY_TASK_TRACK_STARTED = True
REDIS_URL = env("REDIS_URL", default=None)


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
    }
}
# For Database visualization
GRAPH_MODELS = {
    "all_applications": False,
    "group_models": True,
    "app_labels": ["ebustoolbox"],
}

# Turn on hashing and compression for whitenoise
STORAGES = {
    # ...
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {message}",
            "style": "{",
        },
    },
    # Do not show logs with status 200 for map_engine
    "filters": {
        "remove_progress": {
            "()": "core.filters.FilterStatusCode",
            "status_code": 200,
            "search_text": "progress",
        },
        "map_status_no_content": {
            "()": "core.filters.FilterStatusCode",
            "status_code": 204,
            "search_text": "/map/stations_mvt_mvt/",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "filters": ["remove_progress"],
            "formatter": "simple",
        },
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": BASE_DIR
            / "logs/info.log",  # Adjust the path based on  your project structure
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": env.str("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "custom": {
            "handlers": ["console", "file"],
            "level": env.str("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "de"
LANGUAGES = [
    ("de", _("German")),
    ("en", _("English")),
]
# Set the directory where Django will look for translations
LOCALE_PATHS = [
    BASE_DIR / "locale",  # Adjust the path based on  your project structure
]
TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Deny is the default value. If other values are needed give the view the appropriate decorator
# see https://docs.djangoproject.com/en/5.2/ref/clickjacking/
X_FRAME_OPTIONS = "DENY"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
UPLOAD_PATH = "uploads/"
MEDIA_ROOT = env.str("DJANGO_MEDIA_ROOT", "media/")

# Optional: maximum allowed file size for uploads.
# Given in KB, stored in Bytes. Default 64 MB.
MAX_FILE_SIZE_B = env.int("DJANGO_MAX_FILE_SIZE_KB", 64000) << 10

# The maximum number of files per uploaded zip file
MAX_FILE_SIZE_B = env.int("DJANGO_MAX_ZIP_FILES_NR,", 100)


# while the above line checks all the app folders for static folders the below one can be a list of
# general static file folders
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

TAILWIND_APP_NAME = "tailwind_theme"
INTERNAL_IPS = ["localhost", "127.0.0.1"]


# NOTE: By default these are secure settings. Can always be explicitly overwritten by .env
# Small value for testing, maybe increase?
# https://docs.djangoproject.com/en/5.1/ref/middleware/#http-strict-transport-security
SECURE_HSTS_SECONDS = env.bool("DJANGO_SECURE_HSTS_SECONDS", default=60)
# https://docs.djangoproject.com/en/dev/ref/settings/#secure-ssl-redirect
SECURE_SSL_REDIRECT = env.bool("DJANGO_SECURE_SSL_REDIRECT", default=True)
SESSION_COOKIE_SECURE = env.bool("DJANGO_SESSION_COOKIE_SECURE", default=True)
CSRF_COOKIE_SECURE = env.bool("DJANGO_CSRF_COOKIE_SECURE", default=True)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True)
SECURE_HSTS_PRELOAD = env.bool("DJANGO_SECURE_HSTS_PRELOAD", default=True)
# https://docs.djangoproject.com/en/dev/ref/settings/#secure-proxy-ssl-header
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# under which URL can server be reached? Used in email verification
DJANGO_HOST_URL = env("DJANGO_HOST_URL", default="").rstrip('/')
if not DJANGO_HOST_URL:
    print("No DJANGO_HOST_URL set, emails might contain only partial links")

# NOTE: Explicitly setting local development will use unsecure development defaults instead
if env.bool("DJANGO_LOCAL_DEVELOPMENT", default=False):
    # NOTE: Development defaults
    SECURE_HSTS_SECONDS = env.bool("DJANGO_SECURE_HSTS_SECONDS", default=0)
    # https://docs.djangoproject.com/en/dev/ref/settings/#secure-ssl-redirect
    SECURE_SSL_REDIRECT = env.bool("DJANGO_SECURE_SSL_REDIRECT", default=False)
    SESSION_COOKIE_SECURE = env.bool("DJANGO_SESSION_COOKIE_SECURE", default=False)
    CSRF_COOKIE_SECURE = env.bool("DJANGO_CSRF_COOKIE_SECURE", default=False)
    # https://docs.djangoproject.com/en/dev/ref/settings/#secure-proxy-ssl-header
    SECURE_PROXY_SSL_HEADER = env.tuple("SECURE_PROXY_SSL_HEADER", default=None)

    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True)
    SECURE_HSTS_PRELOAD = env.bool("DJANGO_SECURE_HSTS_PRELOAD", default=True)
