# Generated by Django 4.2.4 on 2023-08-23 12:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPCtool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flurstueck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.CharField(max_length=50)),
                ('scenario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=50)),
                ('scenario', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='busoutline',
            name='quality',
            field=models.IntegerField(default=0),
        ),
    ]
