# Generated by Django 4.2.4 on 2023-09-04 11:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPCtool', '0002_flurstueck_tree_busoutline_quality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busoutline',
            old_name='scenario',
            new_name='scenario_ID',
        ),
        migrations.RenameField(
            model_name='flurstueck',
            old_name='scenario',
            new_name='scenario_ID',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='scenario',
            new_name='scenario_ID',
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=50)),
                ('scenario_ID', models.CharField(max_length=50)),
                ('busses', models.ManyToManyField(to='HPCtool.busoutline')),
                ('flurstück', models.ManyToManyField(to='HPCtool.flurstueck')),
                ('trees', models.ManyToManyField(to='HPCtool.tree')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=50)),
                ('scenario_ID', models.CharField(max_length=50)),
                ('stations', models.ManyToManyField(to='HPCtool.station')),
            ],
        ),
    ]
