# Generated by Django 4.2.4 on 2023-09-06 07:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPCtool', '0003_rename_scenario_busoutline_scenario_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cyclepath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=50)),
                ('scenario_ID', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentialArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.CharField(max_length=50)),
                ('scenario_ID', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='geom',
        ),
        migrations.AddField(
            model_name='station',
            name='charge_pwr',
            field=models.CharField(default='MV', max_length=10),
        ),
    ]
