# Generated by Django 4.2.4 on 2023-09-06 07:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HPCtool', '0004_cyclepath_residentialarea_remove_scenario_geom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclepath',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
