# Generated by Django 4.2.4 on 2023-09-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPCtool', '0005_alter_cyclepath_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('scenario_ID', models.CharField(max_length=50)),
                ('geom_type', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=150)),
                ('layer_name', models.CharField(max_length=50)),
                ('dist_red', models.FloatField()),
                ('dist_green', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('scenario_ID', models.CharField(max_length=50)),
                ('bus_length', models.FloatField()),
                ('park_distance', models.FloatField()),
                ('max_curvature', models.FloatField()),
                ('criteria', models.ManyToManyField(to='HPCtool.criterion')),
            ],
        ),
    ]
