# Generated by Django 4.2.4 on 2023-10-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPCtool', '0006_criterion_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='charge_pwr',
        ),
        migrations.AddField(
            model_name='station',
            name='charge_power',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='station',
            name='charge_unit',
            field=models.CharField(default='kW', max_length=10),
        ),
        migrations.AddField(
            model_name='station',
            name='station_power',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='station',
            name='station_unit',
            field=models.CharField(default='kW', max_length=10),
        ),
    ]
