# Generated by Django 4.2.4 on 2023-10-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HPCtool', '0007_remove_station_charge_pwr_station_charge_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='voltage_level',
            field=models.CharField(default='MV', max_length=10),
        ),
    ]
