# Generated by Django 5.0.6 on 2024-06-20 13:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elevation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("raster", django.contrib.gis.db.models.fields.RasterField(null=True, srid=4326)),
            ],
        ),
    ]
