# Generated by Django 5.1.6 on 2025-08-04 15:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField(db_index=True)),
                ("dwd_id", models.CharField(max_length=10)),
                ("geom", django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("time", models.DateTimeField()),
                ("air_temperature", models.FloatField(null=True)),
                (
                    "weatherstation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="temperatures.weatherstation",
                    ),
                ),
            ],
        ),
    ]
