# Generated by Django 5.1.6 on 2025-08-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("temperatures", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherstation",
            name="dwd_id",
            field=models.IntegerField(unique=True),
        ),
    ]
