# Generated by Django 5.1.6 on 2025-08-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temperatures", "0002_alter_weatherstation_dwd_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherstation",
            name="dwd_id",
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
