# Generated by Django 5.0.6 on 2024-11-26 08:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import models

from django.db import migrations, connection


def enable_pg_trgm_extension(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("admin_level", models.IntegerField(default=4)),
                ("osm_id", models.BigIntegerField(unique=True)),
                ("last_check", models.DateTimeField(null=True)),
                (
                    "upper_admin_area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_scrapers.adminarea",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("osm_id", models.BigIntegerField(unique=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(dim=3, null=True, srid=4326),
                ),
                (
                    "admin_area",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_scrapers.adminarea",
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            code=enable_pg_trgm_extension,
        ),
        migrations.AlterField(
            model_name="busstation",
            name="admin_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="data_scrapers.adminarea"
            ),
        ),
    ]
