# Generated by Django 5.0.6 on 2024-11-08 10:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("osm_id", models.IntegerField(unique=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(dim=3, null=True, srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("osm_id", models.IntegerField(unique=True)),
                ("last_check", models.DateTimeField()),
            ],
        ),
    ]
