# Generated by Django 5.0.6 on 2024-11-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_scrapers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busstation",
            name="osm_id",
            field=models.BigIntegerField(unique=True),
        ),
    ]
