# Generated by Django 5.1.4 on 2025-05-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_scrapers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adminarea",
            old_name="last_check",
            new_name="updated_at",
        ),
    ]
