# Generated by Django 5.1.6 on 2025-05-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_scrapers", "0002_rename_last_check_adminarea_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminarea",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="busstation",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
