# Generated by Django 5.0.6 on 2024-11-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_scrapers", "0002_alter_busstation_osm_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="osm_id",
            field=models.BigIntegerField(unique=True),
        ),
    ]
