# Generated by Django 5.0.6 on 2024-11-08 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_scrapers", "0003_alter_state_osm_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("admin_level", models.IntegerField(default=4)),
                ("osm_id", models.BigIntegerField(unique=True)),
                ("last_check", models.DateTimeField()),
                (
                    "upper_admin_area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_scrapers.adminarea",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="State",
        ),
        migrations.AddField(
            model_name="busstation",
            name="admin_area",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="data_scrapers.adminarea"
            ),
            preserve_default=False,
        ),
    ]
