# Generated by Django 5.0.6 on 2024-11-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_scrapers", "0004_adminarea_delete_state_busstation_admin_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminarea",
            name="last_check",
            field=models.DateTimeField(null=True),
        ),
    ]
