# Generated by Django 5.0.6 on 2024-11-11 13:08

from django.db import migrations, connection


def enable_pg_trgm_extension(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")


class Migration(migrations.Migration):

    dependencies = [
        ("data_scrapers", "0005_alter_adminarea_last_check"),
    ]

    operations = [
        migrations.RunPython(enable_pg_trgm_extension),
    ]
